// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2020-2021 NXP
 */

#ifndef DCS_REGS_H__
#define DCS_REGS_H__

#include <immap.h>
#include <bit.h>
#include "dcs_plat_config.h"

#define dcs_out_le32(val, addr)	out_le32((addr), (val))
#define dcs_in_le32(addr)		in_le32((addr))

/* Top Level Configuration Registers */
#define DCS_IP_ID				0x0
#define DCS_IP_RW_TEST_REG			0x4

#define DCS_CLK_DIVIDER_SEL			0x8
#define DCS_CK_EN_SD2				BIT(8)
#define DCS_CK_EN_SD1				BIT(7)
#define DCS_DIV_SEL_SD2_SHIFT			4
#define DCS_DIV_SEL_SD2_MASK			(0x7 << DCS_DIV_SEL_SD2_SHIFT)
#define DCS_DIV_SEL_SD2_DIV_BY_1		(0x0 << DCS_DIV_SEL_SD2_SHIFT)
#define DCS_DIV_SEL_SD2_DIV_BY_2		(0x1 << DCS_DIV_SEL_SD2_SHIFT)
#define DCS_DIV_SEL_SD2_DIV_BY_4		(0x2 << DCS_DIV_SEL_SD2_SHIFT)
#define DCS_DIV_SEL_SD2_DIV_BY_8		(0x3 << DCS_DIV_SEL_SD2_SHIFT)
#define DCS_DIV_SEL_SD2_DIV_BY_16	(0x4 << DCS_DIV_SEL_SD2_SHIFT)
#define DCS_DIV_SEL_SD1_SHIFT		1
#define DCS_DIV_SEL_SD1_MASK			(0x7 << DCS_DIV_SEL_SD1_SHIFT)
#define DCS_DIV_SEL_SD1_DIV_BY_1		(0x0 << DCS_DIV_SEL_SD1_SHIFT)
#define DCS_DIV_SEL_SD1_DIV_BY_2		(0x1 << DCS_DIV_SEL_SD1_SHIFT)
#define DCS_DIV_SEL_SD1_DIV_BY_4		(0x2 << DCS_DIV_SEL_SD1_SHIFT)
#define DCS_DIV_SEL_SD1_DIV_BY_8		(0x3 << DCS_DIV_SEL_SD1_SHIFT)
#define DCS_DIV_SEL_SD1_DIV_BY_16	(0x4 << DCS_DIV_SEL_SD1_SHIFT)
#define DCS_ANALOG_OUT_ENABLE		BIT(0)

#define DCS_CLK_DIVIDER_RESET		0xC
#define DCS_SYNCB			BIT(4)
#define DCS_SYNCA			BIT(3)
//#define DCS_DIV_RST_CAL_ENGINE	BIT(3)
#define DCS_DIV_RST_2			BIT(2)
#define DCS_DIV_RST_1			BIT(1)
#define DCS_DIV_RST			BIT(0)


#define DCS_IQ_PAIR_CLK_SEL_1		0x10
#define DCS_DIV_SEL_DAC_2_SHIFT		6
#define DCS_DIV_SEL_DAC_2_MASK		(0x3 << DCS_DIV_SEL_DAC_2_SHIFT)
#define DCS_DIV_SEL_DAC_2_DIV_BY_1	(0x0 << DCS_DIV_SEL_DAC_2_SHIFT)
#define DCS_DIV_SEL_DAC_2_DIV_BY_2	(0x1 << DCS_DIV_SEL_DAC_2_SHIFT)
#define DCS_DIV_SEL_DAC_2_DIV_BY_4	(0x2 << DCS_DIV_SEL_DAC_2_SHIFT)
#define DCS_DIV_SEL_DAC_2_DIV_BY_8	(0x3 << DCS_DIV_SEL_DAC_2_SHIFT)
#define DCS_DIV_SEL_ADC_2_SHIFT		4
#define DCS_DIV_SEL_ADC_2_MASK		(0x3 << DCS_DIV_SEL_ADC_2_SHIFT)
#define DCS_DIV_SEL_ADC_2_DIV_BY_1	(0x0 << DCS_DIV_SEL_ADC_2_SHIFT)
#define DCS_DIV_SEL_ADC_2_DIV_BY_2	(0x1 << DCS_DIV_SEL_ADC_2_SHIFT)
#define DCS_DIV_SEL_ADC_2_DIV_BY_4	(0x2 << DCS_DIV_SEL_ADC_2_SHIFT)
#define DCS_DIV_SEL_ADC_2_DIV_BY_8	(0x3 << DCS_DIV_SEL_ADC_2_SHIFT)
#define DCS_DIV_SEL_DAC_1_SHIFT		2
#define DCS_DIV_SEL_DAC_1_MASK		(0x3 << DCS_DIV_SEL_DAC_1_SHIFT)
#define DCS_DIV_SEL_DAC_1_DIV_BY_1	(0x0 << DCS_DIV_SEL_DAC_1_SHIFT)
#define DCS_DIV_SEL_DAC_1_DIV_BY_2	(0x1 << DCS_DIV_SEL_DAC_1_SHIFT)
#define DCS_DIV_SEL_DAC_1_DIV_BY_4	(0x2 << DCS_DIV_SEL_DAC_1_SHIFT)
#define DCS_DIV_SEL_DAC_1_DIV_BY_8	(0x3 << DCS_DIV_SEL_DAC_1_SHIFT)
#define DCS_DIV_SEL_ADC_1_SHIFT		0
#define DCS_DIV_SEL_ADC_1_MASK		(0x3 << DCS_DIV_SEL_ADC_1_SHIFT)
#define DCS_DIV_SEL_ADC_1_DIV_BY_1	(0x0 << DCS_DIV_SEL_ADC_1_SHIFT)
#define DCS_DIV_SEL_ADC_1_DIV_BY_2	(0x1 << DCS_DIV_SEL_ADC_1_SHIFT)
#define DCS_DIV_SEL_ADC_1_DIV_BY_4	(0x2 << DCS_DIV_SEL_ADC_1_SHIFT)
#define DCS_DIV_SEL_ADC_1_DIV_BY_8	(0x3 << DCS_DIV_SEL_ADC_1_SHIFT)

#define DCS_CAL_ENGINE_CTRL		0x14
#define DCS_LOW_POWER_CFG		0x18

#define DCS_GLOBAL_SYNC_CTRL		0x1C

/* Calibration Engine ALU Programming Registers */
#define DCS_ALU_STEW_WORD_0		0x80
#define DCS_ALU_STEW_WORD_1		0x84
#define DCS_ALU_STEW_ALIGN_0		0x88
#define DCS_ALU_STEW_ALIGN_1		0x8C
#define DCS_ALU_STEW_WRITE		0x90
#define DCS_ALU_DBG_DATA		0x94
#define DCS_ALU_INPUT_DATA		0x98
#define DCS_ALU_OUTPUT_DATA		0x9C
#define DCS_ALU_CONFIG			0xA0
#define DCS_ALU_DEBUG_CTRL		0xB4
#define DCS_ALU_DECISION_TREE_DATA	0xBC
#define DCS_BG_CAL_ALU_ACC0		0xC0
#define DCS_BG_CAL_ALU_ACC1		0xC4
#define DCS_BG_CAL_ALU_ACC2		0xC8
#define DCS_BG_CAL_ALU_ACC3		0xCC
#define DCS_BG_CAL_ALU_CONST1		0xD0
#define DCS_BG_CAL_ALU_CONST2		0xD4

/* General Calibration Configuration Registers */
#define DCS_BG_CAL_CORR_AVG_COUNT	0x100
#define DCS_ADC_GEN_CONFIG_1		0x104
#define DCS_ADC_GEN_CONFIG_2		0x108
#define DCS_ADC_CONFIG_RA_GAIN		0x10C
#define DCS_ADC_CONFIG_RESERVE_2	0x110

/* Calibration Engine Control Unit (CU) Programming Registers */


/* Conversion Pair 1 Registers */
// PAIR_1 ADC_ENABLE
#define DCS_PAIR_1_ADC_ENABLE		0x800
#define DCS_PAIR_1_ENABLE_ADC_Q		BIT(2)
#define DCS_PAIR_1_ENABLE_ADC_I		BIT(1)
#define DCS_PAIR_1_START_ADC_IQ		BIT(0)

// PAIR_1 ADC_IQPAIR_MODE_CONTROL RW, DEF: 0x08 0x804
#define DCS_PAIR_1_ADC_IQPAIR_MODE_CONTROL 	0x804
#define	DCS_PAIR_1_TXCLK_FORCE_ON		BIT(5)
#define	DCS_PAIR_1_RXCLK_FORCE_ON		BIT(4)
#define	DCS_PAIR_1_CH_SEL_Q			BIT(3)
#define	DCS_PAIR_1_CH_SEL_I			BIT(2)
#define	DCS_PAIR_1_CKPHASE_Q			BIT(1)
#define	DCS_PAIR_1_CKPHASE_I			BIT(0) 

// PAIR_1 ADC_CONFIGURATION_I RW, DEF:0x2810, OFST: 0x808
#define DCS_PAIR_1_ADC_CONFIGURATION_I	 		0x808
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_I_SHIFT		13
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_I_MASK		(0x7 << DCS_PAIR_1_ADC_STG2_EOC_SEL_I_SHIFT)
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_I_0			(0x0 << DCS_PAIR_1_ADC_STG2_EOC_SEL_I_SHIFT)
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_I_1			(0x1 << DCS_PAIR_1_ADC_STG2_EOC_SEL_I_SHIFT)
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_I_SHIFT		11
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_I_MASK		(0x3 << DCS_PAIR_1_ADC_STG1_EOC_SEL_I_SHIFT)
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_I_0			(0x0 << DCS_PAIR_1_ADC_STG1_EOC_SEL_I_SHIFT)
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_I_2			(0x2 << DCS_PAIR_1_ADC_STG1_EOC_SEL_I_SHIFT)
#define DCS_PAIR_1_ADC_STG1_BINMODE_I			BIT(1)
#define DCS_PAIR_1_ADC_STG1_REDMODE_I			BIT(0)

// PAIR_1 ADC_AUTOCAL_START_I RW, DEF: 0x0 0x80c
#define DCS_PAIR_1_ADC_AUTOCAL_START_I	 		0x80C
#define DCS_PAIR_1_AUTOCAL_ADC_I			BIT(0)

#define DCS_PAIR_1_ADC_AUTOCAL_RESULTS_I		0x810


// PAIR_1 ADC_MANUAL_CALIBRAION_I	RW, DEF: 0x40128200	0x814
#define DCS_PAIR_1_ADC_MANUAL_CALIBRAION_I 		0x814
#define DCS_PAIR_1_ADC_GEC_EN_ADC_I_SHIFT		30
#define DCS_PAIR_1_ADC_FORCE_COMP2_CODE_I_SHIFT		29
#define DCS_PAIR_1_ADC_FORCE_COMP1_CODE_I_SHIFT		28
#define DCS_PAIR_1_ADC_FORE_GAIN_CAL_EN_I_SHIFT		27
#define DCS_PAIR_1_ADC_RA_OFFSET_CAL_EN_I_SHIFT		26
#define DCS_PAIR_1_ADC_COMP2_CAL_EN_I_SHIFT		25
#define DCS_PAIR_1_ADC_COMP1_CAL_EN_I_SHIFT		24
#define DCS_PAIR_1_ADC_CAP_CAL_EN_I_SHIFT		23

// PAIR_1 ADC_CALIBRATION_DATA_I	RW, DEF: 0x1040000	0x818
#define DCS_PAIR_1_ADC_CALIBRATION_DATA_I 		0x818
#define DCS_PAIR_1_ADC_COMP2_CODE_OVRD_I_SHIFT	20
#define DCS_PAIR_1_ADC_COMP2_CODE_OVRD_I_MASK	(0x3f << DCS_PAIR_1_ADC_COMP2_CODE_OVRD_I_SHIFT)
#define DCS_PAIR_1_ADC_COMP1_CODE_OVRD_I_SHIFT	14
#define DCS_PAIR_1_ADC_COMP1_CODE_OVRD_I_MASK	(0x3f << DCS_PAIR_1_ADC_COMP1_CODE_OVRD_I_SHIFT)
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_M_I_SHIFT	7
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_M_I_MASK		(0x7f << DCS_PAIR_1_ADC_CAP_CAL_CODE_M_I_SHIFT)
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_P_I_SHIFT	0
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_P_I_MASK		(0x7f << DCS_PAIR_1_ADC_CAP_CAL_CODE_P_I_SHIFT)


// PAIR_1 ADC_RESIDUAL_AMPLIFIER_CTRL_I RW, DEF: 0x09 0x81c
#define DCS_PAIR_1_ADC_RESIDUAL_AMPLIFIER_CTRL_I	0x81C
#define DCS_PAIR_1_ADC_RA_GMODE_I_SHIFT			5
#define DCS_PAIR_1_ADC_RA_GMODE_I				BIT(5)
#define DCS_PAIR_1_ADC_RA_THRESH_I_SHIFT			3
#define DCS_PAIR_1_ADC_RA_THRESH_I_MASK			(0x3 << DCS_PAIR_1_ADC_RA_THRESH_I_SHIFT)
#define DCS_PAIR_1_ADC_RA_DEL_I_SHIFT			0
#define DCS_PAIR_1_ADC_RA_DEL_I_MASK				(0x7 << DCS_PAIR_1_ADC_RA_DEL_I_SHIFT)



// PAIR_1 ADC_CAL_STATUS_I	RO	0x820
#define DCS_PAIR_1_ADC_CAL_STATUS_I			0x820
#define DCS_PAIR_1_ADC_CAP_CAL_DONE_I_SHIFT			4
#define DCS_PAIR_1_ADC_CAP_CAL_DONE_I				BIT(4)
#define DCS_PAIR_1_ADC_FORE_GAIN_CAL_DONE_I_SHIFT	3
#define DCS_PAIR_1_ADC_FORE_GAIN_CAL_DONE_I			BIT(3)
#define DCS_PAIR_1_ADC_RA_OFFSET_CAL_DONE_I_SHIFT	2
#define DCS_PAIR_1_ADC_RA_OFFSET_CAL_DONE_I			BIT(2)
#define DCS_PAIR_1_ADC_COMP2_CAL_DONE_I_SHIFT		1
#define DCS_PAIR_1_ADC_COMP2_CAL_DONE_I				BIT(1)
#define DCS_PAIR_1_ADC_COMP1_CAL_DONE_I_SHIFT		0
#define DCS_PAIR_1_ADC_COMP1_CAL_DONE_I				BIT(0)


// PAIR_1 ADC_CONFIGURATION_Q RW, DEF:0x2810, OFST: 0x824
#define DCS_PAIR_1_ADC_CONFIGURATION_Q	 		0x824
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_SHIFT		13
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_MASK		(0x7 << DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_0			(0x0 << DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_1			(0x1 << DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_SHIFT		11
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_MASK		(0x3 << DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_0			(0x0 << DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_2			(0x2 << DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_1_ADC_STG1_BINMODE_Q			BIT(1)
#define DCS_PAIR_1_ADC_STG1_REDMODE_Q			BIT(0)


#define DCS_PAIR_1_ADC_AUTOCAL_START_Q	 		0x828
#define DCS_PAIR_1_AUTOCAL_ADC_Q					BIT(0)

#define DCS_PAIR_1_ADC_AUTOCAL_RESULTS_Q	 	0x82C

// PAIR_1 ADC_MANUAL_CALIBRAION_Q	RW, DEF: 0x40128200	0x830
#define DCS_PAIR_1_ADC_MANUAL_CALIBRAION_Q 		0x830
#define DCS_PAIR_1_ADC_GEC_EN_ADC_Q_SHIFT		30
#define DCS_PAIR_1_ADC_FORCE_COMP2_CODE_Q_SHIFT	29
#define DCS_PAIR_1_ADC_FORCE_COMP1_CODE_Q_SHIFT	28
#define DCS_PAIR_1_ADC_FORE_GAIN_CAL_EN_Q_SHIFT	27
#define DCS_PAIR_1_ADC_RA_OFFSET_CAL_EN_Q_SHIFT	26
#define DCS_PAIR_1_ADC_COMP2_CAL_EN_Q_SHIFT	25
#define DCS_PAIR_1_ADC_COMP1_CAL_EN_Q_SHIFT	24
#define DCS_PAIR_1_ADC_CAP_CAL_EN_Q_SHIFT	23


// PAIR_1 ADC_CALIBRATION_DATA_Q	RW, DEF: 0x1040000	0x834
#define DCS_PAIR_1_ADC_CALIBRATION_DATA_Q 		0x834
#define DCS_PAIR_1_ADC_COMP2_CODE_OVRD_Q_SHIFT	20
#define DCS_PAIR_1_ADC_COMP2_CODE_OVRD_Q_MASK	(0x3f << DCS_PAIR_1_ADC_COMP2_CODE_OVRD_Q_SHIFT)
#define DCS_PAIR_1_ADC_COMP1_CODE_OVRD_Q_SHIFT	14
#define DCS_PAIR_1_ADC_COMP1_CODE_OVRD_Q_MASK	(0x3f << DCS_PAIR_1_ADC_COMP1_CODE_OVRD_Q_SHIFT)
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_M_Q_SHIFT	7
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_M_Q_MASK		(0x7f << DCS_PAIR_1_ADC_CAP_CAL_CODE_M_Q_SHIFT)
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_P_Q_SHIFT	0
#define DCS_PAIR_1_ADC_CAP_CAL_CODE_P_Q_MASK		(0x7f << DCS_PAIR_1_ADC_CAP_CAL_CODE_P_Q_SHIFT)


// PAIR_1 ADC_RESIDUAL_AMPLIFIER_CTRL_Q RW, DEF: 0x09 0x838
#define DCS_PAIR_1_ADC_RESIDUAL_AMPLIFIER_CTRL_Q	0x838
#define DCS_PAIR_1_ADC_RA_GMODE_Q_SHIFT			5
#define DCS_PAIR_1_ADC_RA_GMODE_Q				BIT(5)
#define DCS_PAIR_1_ADC_RA_THRESH_Q_SHIFT			3
#define DCS_PAIR_1_ADC_RA_THRESH_Q_MASK			(0x3 << DCS_PAIR_1_ADC_RA_THRESH_Q_SHIFT)
#define DCS_PAIR_1_ADC_RA_DEL_Q_SHIFT			0
#define DCS_PAIR_1_ADC_RA_DEL_Q_MASK				(0x7 << DCS_PAIR_1_ADC_RA_DEL_Q_SHIFT)

// PAIR_1 ADC_CAL_STATUS_Q	RO	0x83c
#define DCS_PAIR_1_ADC_CAL_STATUS_Q					0x83C
#define DCS_PAIR_1_ADC_CAP_CAL_DONE_Q_SHIFT			4
#define DCS_PAIR_1_ADC_CAP_CAL_DONE_Q				BIT(4)
#define DCS_PAIR_1_ADC_FORE_GAIN_CAL_DONE_Q_SHIFT	3
#define DCS_PAIR_1_ADC_FORE_GAIN_CAL_DONE_Q			BIT(3)
#define DCS_PAIR_1_ADC_RA_OFFSET_CAL_DONE_Q_SHIFT	2
#define DCS_PAIR_1_ADC_RA_OFFSET_CAL_DONE_Q			BIT(2)
#define DCS_PAIR_1_ADC_COMP2_CAL_DONE_Q_SHIFT		1
#define DCS_PAIR_1_ADC_COMP2_CAL_DONE_Q				BIT(1)
#define DCS_PAIR_1_ADC_COMP1_CAL_DONE_Q_SHIFT		0
#define DCS_PAIR_1_ADC_COMP1_CAL_DONE_Q				BIT(0)


// PAIR_1 ADC_MISC_CTRL	RW, DEF: 0x000000	0x840
#define DCS_PAIR_1_ADC_MISC_CTRL					0x840
#define DCS_PAIR_1_ADC_FLIP_CAPS_EN_SHIFT		16
#define DCS_PAIR_1_ADC_FLIP_CAPS_EN				BIT(16)
#define DCS_PAIR_1_ADC_PIPE_STG2_SHIFT			14
#define DCS_PAIR_1_ADC_PIPE_STG2_1				(0x1 << DCS_PAIR_1_ADC_PIPE_STG2_SHIFT)
#define DCS_PAIR_1_ADC_PIPE_STG2_MASK			(0x11 << DCS_PAIR_1_ADC_PIPE_STG2_SHIFT)
#define DCS_PAIR_1_ADC_CLAMP_EN_SHIFT			3
#define DCS_PAIR_1_ADC_CLAMP_EN					BIT(3)
#define DCS_PAIR_1_ADC_LDO_RFBSEL_SHIFT			4
#define DCS_PAIR_1_ADC_LDO_RFBSEL_2	 			(0x2 << DCS_PAIR_1_ADC_LDO_RFBSEL_SHIFT)
#define DCS_PAIR_1_ADC_LDO_RFBSEL_MASK			(0xf << DCS_PAIR_1_ADC_LDO_RFBSEL_SHIFT)


#define DCS_PAIR_1_DAC_CTRL						0x844
#define DCS_PAIR_1_DAC_ENABLE					BIT(0)

//PAIR_1 DAC_I_CONFIG RW, DEF: 0x00003 0x848
#define DCS_PAIR_1_DAC_I_CONFIG					0x848
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_SHIFT		9
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_MASK		(0x3f << DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_SHIFT)
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_GFAST		(0xe  << DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_SHIFT)
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_VDSL		(0xe  << DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_SHIFT)
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_WIFI		(0x3e << DCS_PAIR_1_DAC_LFSR_DAC_PROG_I_SHIFT)

#define DCS_PAIR_1_DAC_I_LFSR_SEED				0x84C

// PAIR_1 DAC_Q_CONFIG RW, DEF: 0x00003 0x850
#define DCS_PAIR_1_DAC_Q_CONFIG					0x850
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_SHIFT		9
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_MASK		(0x3f << DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_SHIFT)
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_GFAST		(0xe  << DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_SHIFT)
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_VDSL		(0xe  << DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_SHIFT)
#define DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_WIFI		(0x3e << DCS_PAIR_1_DAC_LFSR_DAC_PROG_Q_SHIFT)


#define DCS_PAIR_1_DAC_Q_LFSR_SEED				0x854
#define DCS_PAIR_1_CAL_PN_SEQ_CTRL				0x858

/* Conversion Pair 2 Registers */
// PAIR_2 ADC_ENABLE RW, DEF: 0x0 0x900
#define DCS_PAIR_2_ADC_ENABLE					0x900
#define DCS_PAIR_2_ENABLE_ADC_Q					BIT(2)
#define DCS_PAIR_2_ENABLE_ADC_I					BIT(1)
#define DCS_PAIR_2_START_ADC_IQ					BIT(0)

// PAIR_2 ADC_IQPAIR_MODE_CONTROL RW, DEF: 0x08 0x904
#define DCS_PAIR_2_ADC_IQPAIR_MODE_CONTROL 		0x904
#define	DCS_PAIR_2_TXCLK_FORCE_ON				BIT(5)
#define	DCS_PAIR_2_RXCLK_FORCE_ON				BIT(4)
#define	DCS_PAIR_2_CH_SEL_Q						BIT(3)
#define	DCS_PAIR_2_CH_SEL_I						BIT(2)
#define	DCS_PAIR_2_CKPHASE_Q						BIT(1)
#define	DCS_PAIR_2_CKPHASE_I						BIT(0)

// PAIR_2 ADC_CONFIGURATION_I RW, DEF: 0x2810 0x908
#define DCS_PAIR_2_ADC_CONFIGURATION_I	 		0x908
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_I_SHIFT		13
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_I_MASK		(0x7 << DCS_PAIR_2_ADC_STG2_EOC_SEL_I_SHIFT)
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_I_0			(0x0 << DCS_PAIR_2_ADC_STG2_EOC_SEL_I_SHIFT)
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_I_1			(0x1 << DCS_PAIR_2_ADC_STG2_EOC_SEL_I_SHIFT)
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_I_SHIFT		11
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_I_MASK		(0x3 << DCS_PAIR_2_ADC_STG1_EOC_SEL_I_SHIFT)
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_I_0			(0x0 << DCS_PAIR_2_ADC_STG1_EOC_SEL_I_SHIFT)
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_I_2			(0x2 << DCS_PAIR_2_ADC_STG1_EOC_SEL_I_SHIFT)
#define DCS_PAIR_2_ADC_STG1_BINMODE_I			BIT(1)
#define DCS_PAIR_2_ADC_STG1_REDMODE_I			BIT(0)


// PAIR_2 ADC_AUTOCAL_START_I RW, DEF: 0x0 0x90c
#define DCS_PAIR_2_ADC_AUTOCAL_START_I	 		0x90C
#define DCS_PAIR_2_AUTOCAL_ADC_I					BIT(0)

#define DCS_PAIR_2_ADC_AUTOCAL_RESULTS_I	 	0x910

// PAIR_2 ADC_MANUAL_CALIBRAION_I	RW, DEF: 0x40128200	0x914
#define DCS_PAIR_2_ADC_MANUAL_CALIBRAION_I 		0x914
#define DCS_PAIR_2_ADC_GEC_EN_ADC_I_SHIFT		30
#define DCS_PAIR_2_ADC_FORCE_COMP2_CODE_I_SHIFT	29
#define DCS_PAIR_2_ADC_FORCE_COMP1_CODE_I_SHIFT	28
#define DCS_PAIR_2_ADC_FORE_GAIN_CAL_EN_I_SHIFT	27
#define DCS_PAIR_2_ADC_RA_OFFSET_CAL_EN_I_SHIFT	26
#define DCS_PAIR_2_ADC_COMP2_CAL_EN_I_SHIFT	25
#define DCS_PAIR_2_ADC_COMP1_CAL_EN_I_SHIFT	24
#define DCS_PAIR_2_ADC_CAP_CAL_EN_I_SHIFT	23


// PAIR_2 ADC_CALIBRATION_DATA_I	RW, DEF: 0x1040000	0x918
#define DCS_PAIR_2_ADC_CALIBRATION_DATA_I 		0x918
#define DCS_PAIR_2_ADC_COMP2_CODE_OVRD_I_SHIFT	20
#define DCS_PAIR_2_ADC_COMP2_CODE_OVRD_I_MASK	(0x3f << DCS_PAIR_2_ADC_COMP2_CODE_OVRD_I_SHIFT)
#define DCS_PAIR_2_ADC_COMP1_CODE_OVRD_I_SHIFT	14
#define DCS_PAIR_2_ADC_COMP1_CODE_OVRD_I_MASK	(0x3f << DCS_PAIR_2_ADC_COMP1_CODE_OVRD_I_SHIFT)
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_M_I_SHIFT	7
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_M_I_MASK		(0x7f << DCS_PAIR_2_ADC_CAP_CAL_CODE_M_I_SHIFT)
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_P_I_SHIFT	0
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_P_I_MASK		(0x7f << DCS_PAIR_2_ADC_CAP_CAL_CODE_P_I_SHIFT)


// PAIR_2 ADC_RESIDUAL_AMPLIFIER_CTRL_I RW, DEF: 0x09 0x91c
#define DCS_PAIR_2_ADC_RESIDUAL_AMPLIFIER_CTRL_I	0x91C
#define DCS_PAIR_2_ADC_RA_GMODE_I_SHIFT			5
#define DCS_PAIR_2_ADC_RA_GMODE_I				BIT(5)
#define DCS_PAIR_2_ADC_RA_THRESH_I_SHIFT			3
#define DCS_PAIR_2_ADC_RA_THRESH_I_MASK			(0x3 << DCS_PAIR_2_ADC_RA_THRESH_I_SHIFT)
#define DCS_PAIR_2_ADC_RA_DEL_I_SHIFT			0
#define DCS_PAIR_2_ADC_RA_DEL_I_MASK				(0x7 << DCS_PAIR_2_ADC_RA_DEL_I_SHIFT)


// PAIR_2 ADC_CAL_STATUS_I	RO	0x920
#define DCS_PAIR_2_ADC_CAL_STATUS_I				0x920
#define DCS_PAIR_2_ADC_CAP_CAL_DONE_I_SHIFT			4
#define DCS_PAIR_2_ADC_CAP_CAL_DONE_I				BIT(4)
#define DCS_PAIR_2_ADC_FORE_GAIN_CAL_DONE_I_SHIFT	3
#define DCS_PAIR_2_ADC_FORE_GAIN_CAL_DONE_I			BIT(3)
#define DCS_PAIR_2_ADC_RA_OFFSET_CAL_DONE_I_SHIFT	2
#define DCS_PAIR_2_ADC_RA_OFFSET_CAL_DONE_I			BIT(2)
#define DCS_PAIR_2_ADC_COMP2_CAL_DONE_I_SHIFT		1
#define DCS_PAIR_2_ADC_COMP2_CAL_DONE_I				BIT(1)
#define DCS_PAIR_2_ADC_COMP1_CAL_DONE_I_SHIFT		0
#define DCS_PAIR_2_ADC_COMP1_CAL_DONE_I				BIT(0)



// PAIR_2 ADC_CONFIGURATION_Q RW, DEF: 0x2810 0x924
#define DCS_PAIR_2_ADC_CONFIGURATION_Q	 		0x924
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_Q_SHIFT		13
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_Q_MASK		(0x7 << DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_Q_0			(0x0 << DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_2_ADC_STG2_EOC_SEL_Q_1			(0x1 << DCS_PAIR_1_ADC_STG2_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_Q_SHIFT		11
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_Q_MASK		(0x3 << DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_Q_0			(0x0 << DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_2_ADC_STG1_EOC_SEL_Q_2			(0x2 << DCS_PAIR_1_ADC_STG1_EOC_SEL_Q_SHIFT)
#define DCS_PAIR_2_ADC_STG1_BINMODE_Q			BIT(1)
#define DCS_PAIR_2_ADC_STG1_REDMODE_Q			BIT(0)

// PAIR_2 ADC_AUTOCAL_START_Q RW, DEF: 0x0 0x928
#define DCS_PAIR_2_ADC_AUTOCAL_START_Q	 		0x928
#define DCS_PAIR_2_AUTOCAL_ADC_Q					BIT(0)

#define DCS_PAIR_2_ADC_AUTOCAL_RESULTS_Q	 	0x92C

// PAIR_2 ADC_MANUAL_CALIBRAION_Q	RW, DEF: 0x40128200	0x930
#define DCS_PAIR_2_ADC_MANUAL_CALIBRAION_Q 		0x930
#define DCS_PAIR_2_ADC_GEC_EN_ADC_Q_SHIFT		30
#define DCS_PAIR_2_ADC_FORCE_COMP2_CODE_Q_SHIFT	29
#define DCS_PAIR_2_ADC_FORCE_COMP1_CODE_Q_SHIFT	28
#define DCS_PAIR_2_ADC_FORE_GAIN_CAL_EN_Q_SHIFT	27
#define DCS_PAIR_2_ADC_RA_OFFSET_CAL_EN_Q_SHIFT	26
#define DCS_PAIR_2_ADC_COMP2_CAL_EN_Q_SHIFT	25
#define DCS_PAIR_2_ADC_COMP1_CAL_EN_Q_SHIFT	24
#define DCS_PAIR_2_ADC_CAP_CAL_EN_Q_SHIFT	23


// PAIR_2 ADC_CALIBRATION_DATA_Q	RW, DEF: 0x1040000	0x934
#define DCS_PAIR_2_ADC_CALIBRATION_DATA_Q 		0x934
#define DCS_PAIR_2_ADC_COMP2_CODE_OVRD_Q_SHIFT	20
#define DCS_PAIR_2_ADC_COMP2_CODE_OVRD_Q_MASK	(0x3f << DCS_PAIR_2_ADC_COMP2_CODE_OVRD_Q_SHIFT)
#define DCS_PAIR_2_ADC_COMP1_CODE_OVRD_Q_SHIFT	14
#define DCS_PAIR_2_ADC_COMP1_CODE_OVRD_Q_MASK	(0x3f << DCS_PAIR_2_ADC_COMP1_CODE_OVRD_Q_SHIFT)
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_M_Q_SHIFT	7
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_M_Q_MASK		(0x7f << DCS_PAIR_2_ADC_CAP_CAL_CODE_M_Q_SHIFT)
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_P_Q_SHIFT	0
#define DCS_PAIR_2_ADC_CAP_CAL_CODE_P_Q_MASK		(0x7f << DCS_PAIR_2_ADC_CAP_CAL_CODE_P_Q_SHIFT)




// PAIR_2 ADC_RESIDUAL_AMPLIFIER_CTRL_Q RW, DEF: 0x09 0x938
#define DCS_PAIR_2_ADC_RESIDUAL_AMPLIFIER_CTRL_Q	0x938
#define DCS_PAIR_2_ADC_RA_GMODE_Q_SHIFT			5
#define DCS_PAIR_2_ADC_RA_GMODE_Q				BIT(5)
#define DCS_PAIR_2_ADC_RA_THRESH_Q_SHIFT			3
#define DCS_PAIR_2_ADC_RA_THRESH_Q_MASK			(0x3 << DCS_PAIR_2_ADC_RA_THRESH_Q_SHIFT)
#define DCS_PAIR_2_ADC_RA_DEL_Q_SHIFT			0
#define DCS_PAIR_2_ADC_RA_DEL_Q_MASK				(0x7 << DCS_PAIR_2_ADC_RA_DEL_Q_SHIFT)


// PAIR_2 ADC_CAL_STATUS_Q	RO	0x93c
#define DCS_PAIR_2_ADC_CAL_STATUS_Q				0x93C
#define DCS_PAIR_2_ADC_CAP_CAL_DONE_Q_SHIFT			4
#define DCS_PAIR_2_ADC_CAP_CAL_DONE_Q				BIT(4)
#define DCS_PAIR_2_ADC_FORE_GAIN_CAL_DONE_Q_SHIFT	3
#define DCS_PAIR_2_ADC_FORE_GAIN_CAL_DONE_Q			BIT(3)
#define DCS_PAIR_2_ADC_RA_OFFSET_CAL_DONE_Q_SHIFT	2
#define DCS_PAIR_2_ADC_RA_OFFSET_CAL_DONE_Q			BIT(2)
#define DCS_PAIR_2_ADC_COMP2_CAL_DONE_Q_SHIFT		1
#define DCS_PAIR_2_ADC_COMP2_CAL_DONE_Q				BIT(1)
#define DCS_PAIR_2_ADC_COMP1_CAL_DONE_Q_SHIFT		0
#define DCS_PAIR_2_ADC_COMP1_CAL_DONE_Q				BIT(0)


// PAIR_2 ADC_MISC_CTRL	RW, DEF: 0x000000	0x940
#define DCS_PAIR_2_ADC_MISC_CTRL				0x940
#define DCS_PAIR_2_ADC_FLIP_CAPS_EN_SHIFT		16
#define DCS_PAIR_2_ADC_FLIP_CAPS_EN				BIT(16)
#define DCS_PAIR_2_ADC_PIPE_STG2_SHIFT			14
#define DCS_PAIR_2_ADC_PIPE_STG2_MASK			(0x11 << DCS_PAIR_2_ADC_PIPE_STG2_SHIFT)
#define DCS_PAIR_2_ADC_LDO_RFBSEL_SHIFT			4
#define DCS_PAIR_2_ADC_LDO_RFBSEL_MASK			(0xf << DCS_PAIR_2_ADC_LDO_RFBSEL_SHIFT)
#define DCS_PAIR_2_ADC_CLAMP_EN_SHIFT			3
#define DCS_PAIR_2_ADC_CLAMP_EN					BIT(3)


// PAIR_2 DAC_CTRL RW, DEF: 0x0050 0x944
#define DCS_PAIR_2_DAC_CTRL					0x944
#define DCS_PAIR_2_DAC_ENABLE					BIT(0)

// PAIR_2 DAC_I_CONFIG RW, DEF: 0x00003 0x948
#define DCS_PAIR_2_DAC_I_CONFIG					0x948
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_SHIFT		9
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_MASK		(0x3f << DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_SHIFT)
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_GFAST		(0xe  << DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_SHIFT)
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_VDSL		(0xe  << DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_SHIFT)
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_WIFI		(0x3e << DCS_PAIR_2_DAC_LFSR_DAC_PROG_I_SHIFT)

#define DCS_PAIR_2_DAC_I_LFSR_SEED				0x94C

// PAIR_2 DAC_Q_CONFIG RW, DEF: 0x00003 0x950
#define DCS_PAIR_2_DAC_Q_CONFIG				0x950
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_SHIFT		9
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_MASK		(0x3f << DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_SHIFT)
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_GFAST		(0xe  << DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_SHIFT)
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_VDSL		(0xe  << DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_SHIFT)
#define DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_WIFI		(0x3e << DCS_PAIR_2_DAC_LFSR_DAC_PROG_Q_SHIFT)

#define DCS_PAIR_2_DAC_Q_LFSR_SEED				0x954
#define DCS_PAIR_2_CAL_PN_SEQ_CTRL				0x958


// LOW_POWER_CFG	RW, DEF: 0x1eeee	0x18
#define DCS_LOW_POWER_CFG				0x18
#define DCS_RX_LOW_PWR_CFG_CNVPR1_SHIFT	0
#define DCS_RX_LOW_PWR_CFG_CNVPR1_MASK	(0Xf << DCS_RX_LOW_PWR_CFG_CNVPR1_SHIFT)
#define DCS_TX_LOW_PWR_CFG_CNVPR1_SHIFT	4
#define DCS_TX_LOW_PWR_CFG_CNVPR1_MASK	(0Xf << DCS_TX_LOW_PWR_CFG_CNVPR1_SHIFT)
#define DCS_RX_LOW_PWR_CFG_CNVPR2_SHIFT	8
#define DCS_RX_LOW_PWR_CFG_CNVPR2_MASK	(0Xf << DCS_RX_LOW_PWR_CFG_CNVPR2_SHIFT)
#define DCS_TX_LOW_PWR_CFG_CNVPR2_SHIFT	12
#define DCS_TX_LOW_PWR_CFG_CNVPR2_MASK	(0Xf << DCS_TX_LOW_PWR_CFG_CNVPR2_SHIFT)
#define DCS_CAL_ENGINE_PWR_CFG_SHIFT		16

#define DCS_LOW_POWER_CFG_LDO_DISABLE					BIT(0)	// 1: ADC/DAC LDO is disabled when rxlp/txlp is activated
#define DCS_LOW_POWER_CFG_ANALOG_CORE_DISABLE			BIT(1)	// 1: ADC/DAC Analog Core is disabled when rxlp/txlp is activated
#define DCS_LOW_POWER_CFG_DIGITAL_DISABLE				BIT(2)	// 1: ADC/DAC Digital Core is disabled when rxlp/txlp is activated
#define DCS_LOW_POWER_CFG_ADC_BACKGROUND_CALI_DISABLE	BIT(3)	// 1: ADC Background Calibration is disabled when rxlp is activated
#define DCS_LOW_POWER_CFG_DAC_DEM_DISABLE				BIT(3)	// 1: DAC DEM is disabled when txlp is activated
#define DCS_LOW_POWER_CFG_CAL_ENGINE_PWR_CFG_DISABLE		BIT(DCS_CAL_ENGINE_PWR_CFG_SHIFT)	// Calibration Engine Disable during rxlp1 AND rxlp2 active. When this bit is set to 1 and (rxlp1 AND rxlp2) == 1, the calibration engine will be clock gated.


/* DCS PLL configuration Registers */
#define DCS_PLL_LNX_PLL_CLK_SEL_SIDE_SHIFT			11	// refer from dcs_lynx_clkgen_reg.xlsx
#define DCS_PLL_LNX_PLL_CLK_SEL_SIDE_MASK			(0x3 << DCS_PLL_LNX_PLL_CLK_SEL_SIDE_SHIFT)	// lnx_pll_clk_sel_side[1:0]; bit[12 11]; 00=off, 01=by9, 10=by12, 11=by24
#define DCS_PLL_LNX_PLL_CLK_SEL_TOP_SHIFT			13	// refer from dcs_lynx_clkgen_reg.xlsx
#define DCS_PLL_LNX_PLL_CLK_SEL_TOP_MASK			(0x3 << DCS_PLL_LNX_PLL_CLK_SEL_TOP_SHIFT)	// lnx_pll_clk_sel_top[1:0]; bit[14 13]; 00=off, 01=by9, 10=by12, 11=by24

#define DCS_PLL_LNX_PLL_CLKNET_FULL_RATE_SEL_SHIFT	15	// refer from dcs_lynx_clkgen_reg.xlsx
#define DCS_PLL_LNX_PLL_CLKNET_FULL_RATE_SEL_MASK	(0x1f << DCS_PLL_LNX_PLL_CLKNET_FULL_RATE_SEL_SHIFT)	// lnx_pll_clknet_full_rate_sel[4:0]; bit[19:15]; 0x1e=125MHz, 0xb=122.88MHz, 0x19=156.25MHz, 0x1f=160MHz

#define DCS_PLL_LNX_PLL_CLKOUT_SIDE_EN_SHIFT		26
#define DCS_PLL_LNX_PLL_CLKOUT_SIDE_EN_ENALBE		BIT(DCS_PLL_LNX_PLL_CLKOUT_SIDE_EN_SHIFT)
#define DCS_PLL_LNX_PLL_LS_MACRO_RST_N_SHIFT		31
#define DCS_PLL_LNX_PLL_LS_MACRO_RST_N_ENABLE		BIT(DCS_PLL_LNX_PLL_LS_MACRO_RST_N_SHIFT)

#endif /* DCS_REGS_H__ */


