/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright 2021-2023 NXP */

#ifndef _L1C_DPD_H
#define _L1C_DPD_H

#include "l1c_config.h"

#define VSPA_FECA_PHYS_ADDR_START  0xE5000000
#define VSPA_FECA_TX_RX_OFFSET     0xC8000

#define GEUL_FECA_BASE_ADDR        0xE0000000

#define DPD_COEFF_BUFFER      (VSPA_FECA_PHYS_ADDR_START)
#define TX_QEC_COEFF_BUFFER   (DPD_COEFF_BUFFER + COEFF_BUFFER_SIZE)
#define RX_QEC_COEFF_BUFFER   (TX_QEC_COEFF_BUFFER + COEFF_BUFFER_SIZE)

#define TX_SIGNAL_BUFFER      (RX_QEC_COEFF_BUFFER + COEFF_BUFFER_SIZE)
#define DPD_SIGNAL_BUFFER     (TX_SIGNAL_BUFFER + VSPA_FECA_TX_RX_OFFSET)
#define SRX_SIGNAL_BUFFER     (DPD_SIGNAL_BUFFER + VSPA_FECA_TX_RX_OFFSET)

void vL1CDPDInit();

#endif
