// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2021-2022 NXP
 */

#ifndef __YUC_RFIC_CMD_H__
#define __YUC_RFIC_CMD_H__

#include <types.h>

#include <Time.h>

#include "portmacro.h"
#include "rf_dev.h"
#include "yuc_rfic_common.h"
#include "yuc_init.h"

#define YUC_RFIC_CMD_ADDR         0x0000
#define YUC_RFIC_CMD_RESP_ADDR    0x000a

#define YUC_FWCMD_MASK( o, b )    ( ( ( 1 << ( b ) ) - 1 ) << ( o ) )
#define YUC_W2P( cmd, p, w )      ( ( p ) = ( ( ( w ) & YUC_FWCMD_MASK( ( cmd ## _OFFSET ), ( cmd ## _BITS ) ) ) >> ( cmd ## _OFFSET ) ) )
#define YUC_P2W( cmd, p, w )      ( ( w ) |= ( ( ( p ) << cmd ## _OFFSET ) & YUC_FWCMD_MASK( ( cmd ## _OFFSET ), ( cmd ## _BITS ) ) ) )

/**
 * Below are command word and response word. Please check before updating.
 */
typedef struct YucRficCmd
{
    u16 rrq : 1;
    u16 sd : 1;
    u16 id : 10;
    u16 len : 4;
} __attribute__( ( packed ) ) YucCmd_t;

typedef struct YucRficCmdResp
{
    u16 ew : 1;
    u16 tf : 1;
    u16 id : 10;
    u16 len : 4;
} __attribute__( ( packed ) ) YucCmdResp_t;

typedef struct rxgain_table
{
    uint8_t rfgain_idx;
    uint8_t bbgain_idx;
} __attribute__( ( packed ) )  rxgain_table_t;

#define YUC_CMD_ID_MASK         0x3ff

#define YUC_SM_STANDBY  1 << 0
#define YUC_SM_BBLOOP   1 << 1
#define YUC_SM_TRXPLL   1 << 2
#define YUC_SM_PREPARED 1 << 3
#define YUC_SM_CALPLL   1 << 4
#define YUC_SM_RFLOOP   1 << 5
#define YUC_SM_ACTIVE   1 << 6

#define YUC_SM_ALL ( YUC_SM_STANDBY | YUC_SM_BBLOOP  | YUC_SM_TRXPLL  | YUC_SM_PREPARED \
                     | YUC_SM_CALPLL  | YUC_SM_RFLOOP  | YUC_SM_ACTIVE )

extern int32_t gRXGainLUT[];
extern int32_t gTXGainLUT[];
extern size_t gRXGainLUTsize;
extern size_t gTXGainLUTsize;

/** Array of command handlers indexed by Yucca command code */
cmdHandler_t pYucFwCmdHandlers[ YUC_FW_CMD_MAX_COUNT ];

/**
 * @brief Command handler function for both Firmware comamnds and software commands
 *
 * @param xHandle   RFDevice pointer
 * @param pCmdDesci Command descriptor.
 *
 * @return Returns fail or pass based on result from underlying command.
 */
int32_t iYucHandleCmd( RficHandle_t xHandle,
                       rf_sw_cmd_desc_t * pCmdDesc );

/**
 * @brief Switch from rx to tx or vice versa. This function can be called directly from 
 * L1C for better performance. This way we can avoid coretask based execution for switching 
 * between RX and TX. This is also provided as SW cmd for host based switching.
 *
 * @param xHandle RFDevice pointer
 * @param bIsRx   Enable Recieve mode or not.
 *
 * @return Returns fail or pass based on GPIO settings.
 */
int32_t iYucRficSwitchRxtx( RficHandle_t xHandle,
                          bool bIsRx, bool bIsRxDcCalib);

int32_t iCheckValidFR1Mode( uint32_t fr1_mode );

/**
 * Global definitions for SetPath and GetPath commands.
 */
#define YUC_FWCMD_PATH_WDS            2
#define YUC_FWCMD_GETPATH_WDS         3

#define YUC_FWCMD_PATH_PATH_OFFSET    0
#define YUC_FWCMD_PATH_PATH_BITS      4
#define YUC_FWCMD_PATH_PATH_W2P( p, w )    YUC_W2P( YUC_FWCMD_PATH_PATH, p, w )
#define YUC_FWCMD_PATH_PATH_P2W( p, w )    YUC_P2W( YUC_FWCMD_PATH_PATH, p, w )

#define YUC_FWCMD_PATH_BAND_OFFSET    0
#define YUC_FWCMD_PATH_BAND_BITS      2
#define YUC_FWCMD_PATH_BAND_W2P( p, w )    YUC_W2P( YUC_FWCMD_PATH_BAND, p, w )
#define YUC_FWCMD_PATH_BAND_P2W( p, w )    YUC_P2W( YUC_FWCMD_PATH_BAND, p, w )

#define YUC_FWCMD_PATH_RSSI_OFFSET    2
#define YUC_FWCMD_PATH_RSSI_BITS      2
#define YUC_FWCMD_PATH_RSSI_W2P( p, w )    YUC_W2P( YUC_FWCMD_PATH_RSSI, p, w )
#define YUC_FWCMD_PATH_RSSI_P2W( p, w )    YUC_P2W( YUC_FWCMD_PATH_RSSI, p, w )

#define YUC_FWCMD_PATH_DPD_OFFSET    4
#define YUC_FWCMD_PATH_DPD_BITS      4
#define YUC_FWCMD_PATH_DPD_W2P( p, w )    YUC_W2P( YUC_FWCMD_PATH_DPD, p, w )
#define YUC_FWCMD_PATH_DPD_P2W( p, w )    YUC_P2W( YUC_FWCMD_PATH_DPD, p, w )

#define YUC_FWCMD_PATH_RXBW_OFFSET    8
#define YUC_FWCMD_PATH_RXBW_BITS      4
#define YUC_FWCMD_PATH_RXBW_W2P( p, w )    YUC_W2P( YUC_FWCMD_PATH_RXBW, p, w )
#define YUC_FWCMD_PATH_RXBW_P2W( p, w )    YUC_P2W( YUC_FWCMD_PATH_RXBW, p, w )

#define YUC_FWCMD_PATH_TXBW_OFFSET    12
#define YUC_FWCMD_PATH_TXBW_BITS      4
#define YUC_FWCMD_PATH_TXBW_W2P( p, w )    YUC_W2P( YUC_FWCMD_PATH_TXBW, p, w )
#define YUC_FWCMD_PATH_TXBW_P2W( p, w )    YUC_P2W( YUC_FWCMD_PATH_TXBW, p, w )

/**
 * Global definitions for SetCalPll and GetCalPll commands.
 */
#define YUC_FWCMD_CALPLL_WDS            3
#define YUC_FWCMD_GETCALPLL_WDS         4

#define YUC_FWCMD_CALPLL_MODE_OFFSET    2
#define YUC_FWCMD_CALPLL_MODE_BITS      1
#define YUC_FWCMD_CALPLL_MODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_CALPLL_MODE, p, w )
#define YUC_FWCMD_CALPLL_MODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_CALPLL_MODE, p, w )

#define YUC_FWCMD_CALPLL_FREQ_MSW_OFFSET    8
#define YUC_FWCMD_CALPLL_FREQ_MSW_BITS      8
#define YUC_FWCMD_CALPLL_FREQ_MSW_W2P( p, w )    YUC_W2P( YUC_FWCMD_CALPLL_FREQ_MSW, p, w )
#define YUC_FWCMD_CALPLL_FREQ_MSW_P2W( p, w )    YUC_P2W( YUC_FWCMD_CALPLL_FREQ_MSW, p, w )

#define YUC_FWCMD_CALPLL_FREQ_LSW_OFFSET    0
#define YUC_FWCMD_CALPLL_FREQ_LSW_BITS      16
#define YUC_FWCMD_CALPLL_FREQ_LSW_W2P( p, w )    YUC_W2P( YUC_FWCMD_CALPLL_FREQ_LSW, p, w )
#define YUC_FWCMD_CALPLL_FREQ_LSW_P2W( p, w )    YUC_P2W( YUC_FWCMD_CALPLL_FREQ_LSW, p, w )

#define YUC_FWCMD_CALPLL_CAL_BAND_OFFSET    0
#define YUC_FWCMD_CALPLL_CAL_BAND_BITS      4
#define YUC_FWCMD_CALPLL_CAL_BAND_W2P( p, w )    YUC_W2P( YUC_FWCMD_CALPLL_CAL_BAND, p, w )
#define YUC_FWCMD_CALPLL_CAL_BAND_P2W( p, w )    YUC_P2W( YUC_FWCMD_CALPLL_CAL_BAND, p, w )

/**
 * Global definitions for SetTrxPll and GetTrxPll commands.
 */
#define YUC_FWCMD_TRXPLL_WDS       3
#define YUC_FWCMD_GETTRXPLL_WDS    4

#define YUC_FWCMD_TRXPLL_MODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_CALPLL_MODE, p, w )
#define YUC_FWCMD_TRXPLL_MODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_CALPLL_MODE, p, w )

#define YUC_FWCMD_TRXPLL_VCO_SEL_OFFSET    4
#define YUC_FWCMD_TRXPLL_VCO_SEL_BITS      3
#define YUC_FWCMD_TRXPLL_VCO_SEL_W2P( p, w )     YUC_W2P( YUC_FWCMD_TRXPLL_VCO_SEL, p, w )
#define YUC_FWCMD_TRXPLL_VCO_SEL_P2W( p, w )     YUC_P2W( YUC_FWCMD_TRXPLL_VCO_SEL, p, w )

#define YUC_FWCMD_TRXPLL_FREQ_MSW_W2P( p, w )    YUC_W2P( YUC_FWCMD_CALPLL_FREQ_MSW, p, w )
#define YUC_FWCMD_TRXPLL_FREQ_MSW_P2W( p, w )    YUC_P2W( YUC_FWCMD_CALPLL_FREQ_MSW, p, w )

#define YUC_FWCMD_TRXPLL_FREQ_LSW_W2P( p, w )    YUC_W2P( YUC_FWCMD_CALPLL_FREQ_LSW, p, w )
#define YUC_FWCMD_TRXPLL_FREQ_LSW_P2W( p, w )    YUC_P2W( YUC_FWCMD_CALPLL_FREQ_LSW, p, w )

#define YUC_FWCMD_TRXPLL_CAL_CAP_OFFSET    0
#define YUC_FWCMD_TRXPLL_CAL_CAP_BITS      6
#define YUC_FWCMD_TRXPLL_CAL_CAP_W2P( p, w )    YUC_W2P( YUC_FWCMD_TRXPLL_CAL_CAP, p, w )
#define YUC_FWCMD_TRXPLL_CAL_CAP_P2W( p, w )    YUC_P2W( YUC_FWCMD_TRXPLL_CAL_CAP, p, w )

#define YUC_FWCMD_TRXPLL_CAL_CURRENT_OFFSET    8
#define YUC_FWCMD_TRXPLL_CAL_CURRENT_BITS      8
#define YUC_FWCMD_TRXPLL_CAL_CURRENT_W2P( p, w )    YUC_W2P( YUC_FWCMD_TRXPLL_CAL_CURRENT, p, w )
#define YUC_FWCMD_TRXPLL_CAL_CURRENT_P2W( p, w )    YUC_P2W( YUC_FWCMD_TRXPLL_CAL_CURRENT, p, w )

/**
 * Global definitions for SetGain and GetGain commands.
 */
#define YUC_FWCMD_GAIN_WDS       1
#define YUC_FWCMD_GETGAIN_WDS    8

#define YUC_FWCMD_GAIN_PATH_P2W( p, w )    YUC_P2W( YUC_FWCMD_PATH_PATH, p, w )
#define YUC_FWCMD_GAIN_PATH_W2P( p, w )    YUC_W2P( YUC_FWCMD_PATH_PATH, p, w )

#define YUC_FWCMD_GAIN_MANUAL_OFFSET    4
#define YUC_FWCMD_GAIN_MANUAL_BITS      1
#define YUC_FWCMD_GAIN_MANUAL_W2P( p, w )    YUC_W2P( YUC_FWCMD_GAIN_MANUAL, p, w )
#define YUC_FWCMD_GAIN_MANUAL_P2W( p, w )    YUC_P2W( YUC_FWCMD_GAIN_MANUAL, p, w )

#define YUC_FWCMD_GAIN_CHANNEL_OFFSET    5
#define YUC_FWCMD_GAIN_CHANNEL_BITS      1
#define YUC_FWCMD_GAIN_CHANNEL_W2P( p, w )    YUC_W2P( YUC_FWCMD_GAIN_CHANNEL, p, w )
#define YUC_FWCMD_GAIN_CHANNEL_P2W( p, w )    YUC_P2W( YUC_FWCMD_GAIN_CHANNEL, p, w )

#define YUC_FWCMD_GAIN_HASHMODE_OFFSET    6
#define YUC_FWCMD_GAIN_HASHMODE_BITS      1
#define YUC_FWCMD_GAIN_HASHMODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_GAIN_HASHMODE, p, w )
#define YUC_FWCMD_GAIN_HASHMODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_GAIN_HASHMODE, p, w )

#define YUC_FWCMD_GAIN_TXGAIN_OFFSET    8
#define YUC_FWCMD_GAIN_TXGAIN_BITS      5
#define YUC_FWCMD_GAIN_TXGAIN_W2P( p, w )    YUC_W2P( YUC_FWCMD_GAIN_TXGAIN, p, w )
#define YUC_FWCMD_GAIN_TXGAIN_P2W( p, w )    YUC_P2W( YUC_FWCMD_GAIN_TXGAIN, p, w )

#define YUC_FWCMD_GAIN_BBGAIN_OFFSET    8
#define YUC_FWCMD_GAIN_BBGAIN_BITS      4
#define YUC_FWCMD_GAIN_BBGAIN_W2P( p, w )    YUC_W2P( YUC_FWCMD_GAIN_BBGAIN, p, w )
#define YUC_FWCMD_GAIN_BBGAIN_P2W( p, w )    YUC_P2W( YUC_FWCMD_GAIN_BBGAIN, p, w )

#define YUC_FWCMD_GAIN_RFGAIN_OFFSET    12
#define YUC_FWCMD_GAIN_RFGAIN_BITS      4
#define YUC_FWCMD_GAIN_RFGAIN_W2P( p, w )    YUC_W2P( YUC_FWCMD_GAIN_RFGAIN, p, w )
#define YUC_FWCMD_GAIN_RFGAIN_P2W( p, w )    YUC_P2W( YUC_FWCMD_GAIN_RFGAIN, p, w )

#define YUC_FWCMD_GAIN_RXGAIN_OFFSET    8
#define YUC_FWCMD_GAIN_RXGAIN_BITS      7
#define YUC_FWCMD_GAIN_RXGAIN_W2P( p, w )    YUC_W2P( YUC_FWCMD_GAIN_RXGAIN, p, w )
#define YUC_FWCMD_GAIN_RXGAIN_P2W( p, w )    YUC_P2W( YUC_FWCMD_GAIN_RXGAIN, p, w )

#define YUC_FWCMD_GETGAIN_HASHMODE_OFFSET    5
#define YUC_FWCMD_GETGAIN_HASHMODE_BITS      1
#define YUC_FWCMD_GETGAIN_HASHMODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETGAIN_HASHMODE, p, w )
#define YUC_FWCMD_GETGAIN_HASHMODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETGAIN_HASHMODE, p, w )

#define YUC_FWCMD_GETGAIN_CHANNEL_OFFSET    6
#define YUC_FWCMD_GETGAIN_CHANNEL_BITS      1
#define YUC_FWCMD_GETGAIN_CHANNEL_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETGAIN_CHANNEL, p, w )

#define YUC_FWCMD_GETGAIN_GAINRAW_OFFSET    0
#define YUC_FWCMD_GETGAIN_GAINRAW_BITS      16
#define YUC_FWCMD_GETGAIN_GAINRAW_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETGAIN_GAINRAW, p, w )

#define YUC_FWCMD_GETGAIN_TXGAIN_OFFSET     0
#define YUC_FWCMD_GETGAIN_TXGAIN_BITS       5
#define YUC_FWCMD_GETGAIN_TXGAIN_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETGAIN_TXGAIN, p, w )

/**
 * Global definition for SetBbLoopback command.
 */
#define YUC_FWCMD_BBLOOPBACK_WDS                   1

#define YUC_FWCMD_SETBBLOOPBACK_RECEIVER_OFFSET    0
#define YUC_FWCMD_SETBBLOOPBACK_RECEIVER_BITS      2
#define YUC_FWCMD_SETBBLOOPBACK_RECEIVER_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETBBLOOPBACK_RECEIVER, p, w )
#define YUC_FWCMD_SETBBLOOPBACK_RECEIVER_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETBBLOOPBACK_RECEIVER, p, w )

#define YUC_FWCMD_SETBBLOOPBACK_TXBW_OFFSET    2
#define YUC_FWCMD_SETBBLOOPBACK_TXBW_BITS      2
#define YUC_FWCMD_SETBBLOOPBACK_TXBW_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETBBLOOPBACK_TXBW, p, w )

#define YUC_FWCMD_SETBBLOOPBACK_RXBW_OFFSET    4
#define YUC_FWCMD_SETBBLOOPBACK_RXBW_BITS      4
#define YUC_FWCMD_SETBBLOOPBACK_RXBW_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETBBLOOPBACK_RXBW, p, w )

/**
 * Global definition for SetRFLoopback command.
 */
#define YUC_FWCMD_RFLOOPBACK_WDS                   1

#define YUC_FWCMD_SETRFLOOPBACK_RECEIVER_OFFSET    0
#define YUC_FWCMD_SETRFLOOPBACK_RECEIVER_BITS      2
#define YUC_FWCMD_SETRFLOOPBACK_RECEIVER_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETRFLOOPBACK_RECEIVER, p, w )
#define YUC_FWCMD_SETRFLOOPBACK_RECEIVER_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETRFLOOPBACK_RECEIVER, p, w )

#define YUC_FWCMD_SETRFLOOPBACK_BAND_OFFSET    4
#define YUC_FWCMD_SETRFLOOPBACK_BAND_BITS      2
#define YUC_FWCMD_SETRFLOOPBACK_BAND_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETRFLOOPBACK_BAND, p, w )
#define YUC_FWCMD_SETRFLOOPBACK_BAND_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETRFLOOPBACK_BAND, p, w )

#define YUC_FWCMD_SETRFLOOPBACK_LOOPMODE_OFFSET    8
#define YUC_FWCMD_SETRFLOOPBACK_LOOPMODE_BITS      1
#define YUC_FWCMD_SETRFLOOPBACK_LOOPMODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETRFLOOPBACK_LOOPMODE, p, w )
#define YUC_FWCMD_SETRFLOOPBACK_LOOPMODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETRFLOOPBACK_LOOPMODE, p, w )

#define YUC_FWCMD_SETRFLOOPBACK_RTC_OFFSET    0
#define YUC_FWCMD_SETRFLOOPBACK_RTC_BITS      16
#define YUC_FWCMD_SETRFLOOPBACK_RTC_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETRFLOOPBACK_RTC, p, w )
#define YUC_FWCMD_SETRFLOOPBACK_RTC_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETRFLOOPBACK_RTC, p, w )

/**
 * Global definition for SetRxDc and GetRxDc commands.
 */
#define YUC_FWCMD_RXDC_WDS                9
#define YUC_FWCMD_GETRXDC_WDS             1

#define YUC_FWCMD_RXDC_RECEIVER_OFFSET    0
#define YUC_FWCMD_RXDC_RECEIVER_BITS      2
#define YUC_FWCMD_RXDC_RECEIVER_W2P( p, w )    YUC_W2P( YUC_FWCMD_RXDC_RECEIVER, p, w )
#define YUC_FWCMD_RXDC_RECEIVER_P2W( p, w )    YUC_P2W( YUC_FWCMD_RXDC_RECEIVER, p, w )

#define YUC_FWCMD_RXDC_CHANNEL_OFFSET    4
#define YUC_FWCMD_RXDC_CHANNEL_BITS      1
#define YUC_FWCMD_RXDC_CHANNEL_W2P( p, w )    YUC_W2P( YUC_FWCMD_RXDC_CHANNEL, p, w )
#define YUC_FWCMD_RXDC_CHANNEL_P2W( p, w )    YUC_P2W( YUC_FWCMD_RXDC_CHANNEL, p, w )

#define YUC_FWCMD_RXDC_IQSELECT_OFFSET    8
#define YUC_FWCMD_RXDC_IQSELECT_BITS      1
#define YUC_FWCMD_RXDC_IQSELECT_W2P( p, w )    YUC_W2P( YUC_FWCMD_RXDC_IQSELECT, p, w )
#define YUC_FWCMD_RXDC_IQSELECT_P2W( p, w )    YUC_P2W( YUC_FWCMD_RXDC_IQSELECT, p, w )

#define YUC_FWCMD_RXDC_FINE_OFFSET    0
#define YUC_FWCMD_RXDC_FINE_BITS      6
#define YUC_FWCMD_RXDC_FINE_W2P( p, w )    YUC_W2P( YUC_FWCMD_RXDC_FINE, p, w )
#define YUC_FWCMD_RXDC_FINE_P2W( p, w )    YUC_P2W( YUC_FWCMD_RXDC_FINE, p, w )

#define YUC_FWCMD_RXDC_COARSE_OFFSET    8
#define YUC_FWCMD_RXDC_COARSE_BITS      6
#define YUC_FWCMD_RXDC_COARSE_W2P( p, w )    YUC_W2P( YUC_FWCMD_RXDC_COARSE, p, w )
#define YUC_FWCMD_RXDC_COARSE_P2W( p, w )    YUC_P2W( YUC_FWCMD_RXDC_COARSE, p, w )

/**
 * Global definitions for GetVersion command.
 */
#define YUC_FWCMD_GETVERS_WDS              4

#define YUC_FWCMD_GETVERS_HWVERS_OFFSET    0
#define YUC_FWCMD_GETVERS_HWVERS_BITS      16
#define YUC_FWCMD_GETVERS_HWVERS_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETVERS_HWVERS, p, w )
#define YUC_FWCMD_GETVERS_HWVERS_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETVERS_HWVERS, p, w )

#define YUC_FWCMD_GETVERS_MINVERS_OFFSET    0
#define YUC_FWCMD_GETVERS_MINVERS_BITS      8
#define YUC_FWCMD_GETVERS_MINVERS_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETVERS_MINVERS, p, w )
#define YUC_FWCMD_GETVERS_MINVERS_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETVERS_MINVERS, p, w )

#define YUC_FWCMD_GETVERS_MAJVERS_OFFSET    8
#define YUC_FWCMD_GETVERS_MAJVERS_BITS      4
#define YUC_FWCMD_GETVERS_MAJVERS_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETVERS_MAJVERS, p, w )
#define YUC_FWCMD_GETVERS_MAJVERS_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETVERS_MAJVERS, p, w )

#define YUC_FWCMD_GETVERS_TGTVERS_OFFSET    12
#define YUC_FWCMD_GETVERS_TGTVERS_BITS      4
#define YUC_FWCMD_GETVERS_TGTVERS_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETVERS_TGTVERS, p, w )
#define YUC_FWCMD_GETVERS_TGTVERS_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETVERS_TGTVERS, p, w )

#define YUC_FWCMD_GETVERS_BLDNR_OFFSET    0
#define YUC_FWCMD_GETVERS_BLDNR_BITS      8
#define YUC_FWCMD_GETVERS_BLDNR_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETVERS_BLDNR, p, w )
#define YUC_FWCMD_GETVERS_BLDNR_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETVERS_BLDNR, p, w )

#define YUC_FWCMD_GETVERS_TSTNR_OFFSET    8
#define YUC_FWCMD_GETVERS_TSTNR_BITS      7
#define YUC_FWCMD_GETVERS_TSTNR_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETVERS_TSTNR, p, w )
#define YUC_FWCMD_GETVERS_TSTNR_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETVERS_TSTNR, p, w )

#define YUC_FWCMD_GETVERS_DBGFLG_OFFSET    15
#define YUC_FWCMD_GETVERS_DBGFLG_BITS      1
#define YUC_FWCMD_GETVERS_DBGFLG_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETVERS_DBGFLG, p, w )
#define YUC_FWCMD_GETVERS_DBGFLG_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETVERS_DBGFLG, p, w )

/**
 * Global definitions for Get Sys Status command.
 */
#define YUC_FWCMD_GETSYSSTATUS_WDS           3

#define YUC_FWCMD_GETSYSSTATUS_RTC_OFFSET    0
#define YUC_FWCMD_GETSYSSTATUS_RTC_BITS      16
#define YUC_FWCMD_GETSYSSTATUS_RTC_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_RTC, p, w )
#define YUC_FWCMD_GETSYSSTATUS_RTC_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_RTC, p, w )

#define YUC_FWCMD_GETSYSSTATUS_SYSSTATE_OFFSET    0
#define YUC_FWCMD_GETSYSSTATUS_SYSSTATE_BITS      16
#define YUC_FWCMD_GETSYSSTATUS_SYSSTATE_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_SYSSTATE, p, w )
#define YUC_FWCMD_GETSYSSTATUS_SYSSTATE_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_SYSSTATE, p, w )

#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_LO_OFFSET    0
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_LO_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_LO_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_LO, p, w )
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_LO_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_LO, p, w )

#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_HI_OFFSET    1
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_HI_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_HI_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_HI, p, w )
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_HI_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VCO_HI, p, w )

#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_LO_OFFSET    2
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_LO_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_LO_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_LO, p, w )
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_LO_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_LO, p, w )

#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_HI_OFFSET    3
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_HI_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_HI_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_HI, p, w )
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_HI_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_TRXPLL_VTUNE_HI, p, w )

#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_UNLOCK_OFFSET    4
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_UNLOCK_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_UNLOCK_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_TRXPLL_UNLOCK, p, w )
#define YUC_FWCMD_GETSYSSTATUS_TRXPLL_UNLOCK_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_TRXPLL_UNLOCK, p, w )

#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_LO_OFFSET    10
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_LO_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_LO_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_LO, p, w )
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_LO_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_LO, p, w )

#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_HI_OFFSET    11
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_HI_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_HI_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_HI, p, w )
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_HI_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_CALPLL_VTUNE_HI, p, w )

#define YUC_FWCMD_GETSYSSTATUS_CALPLL_UNLOCK_OFFSET    12
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_UNLOCK_BITS      1
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_UNLOCK_W2P( p, w )    YUC_W2P( YUC_FWCMD_GETSYSSTATUS_CALPLL_UNLOCK, p, w )
#define YUC_FWCMD_GETSYSSTATUS_CALPLL_UNLOCK_P2W( p, w )    YUC_P2W( YUC_FWCMD_GETSYSSTATUS_CALPLL_UNLOCK, p, w )

/**
 * Global definitiosn of SetTxBW, GetTxBw, SetRxBw, GetRxBw
 */
#define YUC_FWCMD_SET_TXRXBW_WDS      2
#define YUC_FWCMD_GET_TXRXBW_WDS      3

#define YUC_FWCMD_TXBW_BW_OFFSET    0
#define YUC_FWCMD_TXBW_BW_BITS      2
#define YUC_FWCMD_TXBW_BW_W2P( p, w )    YUC_W2P( YUC_FWCMD_TXBW_BW, p, w )
#define YUC_FWCMD_TXBW_BW_P2W( p, w )    YUC_P2W( YUC_FWCMD_TXBW_BW, p, w )

#define YUC_FWCMD_RXBW_BW_OFFSET    0
#define YUC_FWCMD_RXBW_BW_BITS      4
#define YUC_FWCMD_RXBW_BW_W2P( p, w )    YUC_W2P( YUC_FWCMD_RXBW_BW, p, w )
#define YUC_FWCMD_RXBW_BW_P2W( p, w )    YUC_P2W( YUC_FWCMD_RXBW_BW, p, w )

#define YUC_FWCMD_TXRXBW_BWFTUNE_OFFSET    0
#define YUC_FWCMD_TXRXBW_BWFTUNE_BITS      5
#define YUC_FWCMD_TXRXBW_BWFTUNE_W2P( p, w )    YUC_W2P( YUC_FWCMD_TXRXBW_BWFTUNE, p, w )
#define YUC_FWCMD_TXRXBW_BWFTUNE_P2W( p, w )    YUC_P2W( YUC_FWCMD_TXRXBW_BWFTUNE, p, w )
#define YUC_FWCMD_TXRXBW_RTC_OFFSET        0
#define YUC_FWCMD_TXRXBW_RTC_BITS          16
#define YUC_FWCMD_TXRXBW_RTC_W2P( p, w )        YUC_W2P( YUC_FWCMD_TXRXBW_RTC, p, w )
#define YUC_FWCMD_TXRXBW_RTC_P2W( p, w )        YUC_P2W( YUC_FWCMD_TXRXBW_RTC, p, w )

/**
 * Global definitiosn of Set/Get Property
 */
#define YUC_FWCMD_SET_PROPERTY_WDS      9
#define YUC_FWCMD_GET_PROPERTY_WDS      9

#define YUC_FWCMD_PROPERTY_ID_OFFSET    0
#define YUC_FWCMD_PROPERTY_ID_BITS      16
#define YUC_FWCMD_PROPERTY_ID_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_ID, p, w )
#define YUC_FWCMD_PROPERTY_ID_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_ID, p, w )

#define YUC_FWCMD_PROPERTY_LENGTH_OFFSET    0
#define YUC_FWCMD_PROPERTY_LENGTH_BITS      16
#define YUC_FWCMD_PROPERTY_LENGTH_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_LENGTH, p, w )
#define YUC_FWCMD_PROPERTY_LENGTH_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_LENGTH, p, w )

#define YUC_FWCMD_PROPERTY_RTC_OFFSET    0
#define YUC_FWCMD_PROPERTY_RTC_BITS      16
#define YUC_FWCMD_PROPERTY_RTC_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_RTC, p, w )
#define YUC_FWCMD_PROPERTY_RTC_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_RTC, p, w )

#define YUC_FWCMD_PROPERTY_VALUE1_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE1_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE1_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE1, p, w )
#define YUC_FWCMD_PROPERTY_VALUE1_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE1, p, w )

#define YUC_FWCMD_PROPERTY_VALUE2_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE2_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE2_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE2, p, w )
#define YUC_FWCMD_PROPERTY_VALUE2_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE2, p, w )

#define YUC_FWCMD_PROPERTY_VALUE3_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE3_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE3_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE3, p, w )
#define YUC_FWCMD_PROPERTY_VALUE3_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE3, p, w )

#define YUC_FWCMD_PROPERTY_VALUE4_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE4_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE4_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE4, p, w )
#define YUC_FWCMD_PROPERTY_VALUE4_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE4, p, w )

#define YUC_FWCMD_PROPERTY_VALUE5_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE5_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE5_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE5, p, w )
#define YUC_FWCMD_PROPERTY_VALUE5_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE5, p, w )

#define YUC_FWCMD_PROPERTY_VALUE6_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE6_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE6_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE6, p, w )
#define YUC_FWCMD_PROPERTY_VALUE6_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE6, p, w )

#define YUC_FWCMD_PROPERTY_VALUE7_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE7_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE7_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE7, p, w )
#define YUC_FWCMD_PROPERTY_VALUE7_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE7, p, w )

#define YUC_FWCMD_PROPERTY_VALUE8_OFFSET    0
#define YUC_FWCMD_PROPERTY_VALUE8_BITS      16
#define YUC_FWCMD_PROPERTY_VALUE8_W2P( p, w )    YUC_W2P( YUC_FWCMD_PROPERTY_VALUE8, p, w )
#define YUC_FWCMD_PROPERTY_VALUE8_P2W( p, w )    YUC_P2W( YUC_FWCMD_PROPERTY_VALUE8, p, w )


#define YUC_FWCMD_SETACTIVE_WDS_IN         1
#define YUC_FWCMD_SETACTIVE_WDS_OUT        2

#define YUC_FWCMD_SETACTIVE_MODE_OFFSET    0
#define YUC_FWCMD_SETACTIVE_MODE_BITS      2
#define YUC_FWCMD_SETACTIVE_MODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETACTIVE_MODE, p, w )
#define YUC_FWCMD_SETACTIVE_MODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETACTIVE_MODE, p, w )

#define YUC_FWCMD_SETACTIVE_DPD_RX_OFFSET    4
#define YUC_FWCMD_SETACTIVE_DPD_RX_BITS      2
#define YUC_FWCMD_SETACTIVE_DPD_RX_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETACTIVE_DPD_RX, p, w )
#define YUC_FWCMD_SETACTIVE_DPD_RX_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETACTIVE_DPD_RX, p, w )

#define YUC_FWCMD_SETACTIVE_RTC_OFFSET    0
#define YUC_FWCMD_SETACTIVE_RTC_BITS      16
#define YUC_FWCMD_SETACTIVE_RTC_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETACTIVE_RTC, p, w )
#define YUC_FWCMD_SETACTIVE_RTC_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETACTIVE_RTC, p, w )

/**
 * Global definition for SetCalRxDc command.
 */
#define YUC_FWCMD_SETCALRXDC_WDS                3

#define YUC_FWCMD_SETCALRXDC_RECEIVER_OFFSET    0
#define YUC_FWCMD_SETCALRXDC_RECEIVER_BITS      2
#define YUC_FWCMD_SETCALRXDC_RECEIVER_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETCALRXDC_RECEIVER, p, w )
#define YUC_FWCMD_SETCALRXDC_RECEIVER_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETCALRXDC_RECEIVER, p, w )

#define YUC_FWCMD_SETCALRXDC_MODE_OFFSET    4
#define YUC_FWCMD_SETCALRXDC_MODE_BITS      1
#define YUC_FWCMD_SETCALRXDC_MODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETCALRXDC_MODE, p, w )
#define YUC_FWCMD_SETCALRXDC_MODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETCALRXDC_MODE, p, w )

#define YUC_FWCMD_SETCALRXDC_IFINE_OFFSET    0
#define YUC_FWCMD_SETCALRXDC_IFINE_BITS      6
#define YUC_FWCMD_SETCALRXDC_IFINE_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETCALRXDC_IFINE, p, w )
#define YUC_FWCMD_SETCALRXDC_IFINE_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETCALRXDC_IFINE, p, w )

#define YUC_FWCMD_SETCALRXDC_ICOARSE_OFFSET    8
#define YUC_FWCMD_SETCALRXDC_ICOARSE_BITS      6
#define YUC_FWCMD_SETCALRXDC_ICOARSE_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETCALRXDC_ICOARSE, p, w )
#define YUC_FWCMD_SETCALRXDC_ICOARSE_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETCALRXDC_ICOARSE, p, w )

#define YUC_FWCMD_SETCALRXDC_QFINE_OFFSET    0
#define YUC_FWCMD_SETCALRXDC_QFINE_BITS      6
#define YUC_FWCMD_SETCALRXDC_QFINE_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETCALRXDC_QFINE, p, w )
#define YUC_FWCMD_SETCALRXDC_QFINE_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETCALRXDC_QFINE, p, w )

#define YUC_FWCMD_SETCALRXDC_QCOARSE_OFFSET    8
#define YUC_FWCMD_SETCALRXDC_QCOARSE_BITS      6
#define YUC_FWCMD_SETCALRXDC_QCOARSE_W2P( p, w )    YUC_W2P( YUC_FWCMD_SETCALRXDC_QCOARSE, p, w )
#define YUC_FWCMD_SETCALRXDC_QCOARSE_P2W( p, w )    YUC_P2W( YUC_FWCMD_SETCALRXDC_QCOARSE, p, w )


/**
 * Global definitiosn of Set/Get Register
 */

#define YUC_FWCMD_SET_REGISTER_WDS      9
#define YUC_FWCMD_SET_REGISTER_MASK_WDS 3
#define YUC_FWCMD_GET_REGISTER_IN_WDS   2
#define YUC_FWCMD_GET_REGISTER_WDS      9

#define YUC_FWCMD_REGISTER_ADDR_OFFSET    0
#define YUC_FWCMD_REGISTER_ADDR_BITS      16
#define YUC_FWCMD_REGISTER_ADDR_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_ADDR, p, w )
#define YUC_FWCMD_REGISTER_ADDR_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_ADDR, p, w )

#define YUC_FWCMD_REGISTER_LENGTH_OFFSET    0
#define YUC_FWCMD_REGISTER_LENGTH_BITS      16
#define YUC_FWCMD_REGISTER_LENGTH_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_LENGTH, p, w )
#define YUC_FWCMD_REGISTER_LENGTH_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_LENGTH, p, w )

#define YUC_FWCMD_REGISTER_MASK_OFFSET    0
#define YUC_FWCMD_REGISTER_MASK_BITS      16
#define YUC_FWCMD_REGISTER_MASK_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_MASK, p, w )
#define YUC_FWCMD_REGISTER_MASK_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_MASK, p, w )

#define YUC_FWCMD_REGISTER_VALUE1_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE1_BITS      16
#define YUC_FWCMD_REGISTER_VALUE1_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE1, p, w )
#define YUC_FWCMD_REGISTER_VALUE1_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE1, p, w )

#define YUC_FWCMD_REGISTER_VALUE2_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE2_BITS      16
#define YUC_FWCMD_REGISTER_VALUE2_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE2, p, w )
#define YUC_FWCMD_REGISTER_VALUE2_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE2, p, w )

#define YUC_FWCMD_REGISTER_VALUE3_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE3_BITS      16
#define YUC_FWCMD_REGISTER_VALUE3_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE3, p, w )
#define YUC_FWCMD_REGISTER_VALUE3_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE3, p, w )

#define YUC_FWCMD_REGISTER_VALUE4_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE4_BITS      16
#define YUC_FWCMD_REGISTER_VALUE4_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE4, p, w )
#define YUC_FWCMD_REGISTER_VALUE4_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE4, p, w )

#define YUC_FWCMD_REGISTER_VALUE5_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE5_BITS      16
#define YUC_FWCMD_REGISTER_VALUE5_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE5, p, w )
#define YUC_FWCMD_REGISTER_VALUE5_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE5, p, w )

#define YUC_FWCMD_REGISTER_VALUE6_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE6_BITS      16
#define YUC_FWCMD_REGISTER_VALUE6_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE6, p, w )
#define YUC_FWCMD_REGISTER_VALUE6_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE6, p, w )

#define YUC_FWCMD_REGISTER_VALUE7_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE7_BITS      16
#define YUC_FWCMD_REGISTER_VALUE7_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE7, p, w )
#define YUC_FWCMD_REGISTER_VALUE7_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE7, p, w )

#define YUC_FWCMD_REGISTER_VALUE8_OFFSET    0
#define YUC_FWCMD_REGISTER_VALUE8_BITS      16
#define YUC_FWCMD_REGISTER_VALUE8_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_VALUE8, p, w )
#define YUC_FWCMD_REGISTER_VALUE8_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_VALUE8, p, w )

#define YUC_FWCMD_REGISTER_RTC_OFFSET    0
#define YUC_FWCMD_REGISTER_RTC_BITS      16
#define YUC_FWCMD_REGISTER_RTC_W2P( p, w )    YUC_W2P( YUC_FWCMD_REGISTER_RTC, p, w )
#define YUC_FWCMD_REGISTER_RTC_P2W( p, w )    YUC_P2W( YUC_FWCMD_REGISTER_RTC, p, w )

 /* Global definitiosn of GetTemperature */

#define YUC_FWCMD_GET_TEMPERATURE_WDS   3

#define YUC_FWCMD_TEMPERATURE_RTC_OFFSET    0
#define YUC_FWCMD_TEMPERATURE_RTC_BITS      16
#define YUC_FWCMD_TEMPERATURE_RTC_W2P( p, w )    YUC_W2P( YUC_FWCMD_TEMPERATURE_RTC, p, w )
#define YUC_FWCMD_TEMPERATURE_RTC_P2W( p, w )    YUC_P2W( YUC_FWCMD_TEMPERATURE_RTC, p, w )

#define YUC_FWCMD_TEMPERATURE_OFFSET    0
#define YUC_FWCMD_TEMPERATURE_BITS      16
#define YUC_FWCMD_TEMPERATURE_W2P( p, w )    YUC_W2P( YUC_FWCMD_TEMPERATURE, p, w )
#define YUC_FWCMD_TEMPERATURE_P2W( p, w )    YUC_P2W( YUC_FWCMD_TEMPERATURE, p, w )

#define YUC_FWCMD_TEMPERATURE_VALUERAW_OFFSET    0
#define YUC_FWCMD_TEMPERATURE_VALUERAW_BITS      16
#define YUC_FWCMD_TEMPERATURE_VALUERAW_W2P( p, w )    YUC_W2P( YUC_FWCMD_TEMPERATURE_VALUERAW, p, w )
#define YUC_FWCMD_TEMPERATURE_VALUERAW_P2W( p, w )    YUC_P2W( YUC_FWCMD_TEMPERATURE_VALUERAW, p, w )

/**
 * Global definition for Set/Get RSSI command.
 */
#define YUC_FWCMD_SETRSSI_WDS             4
#define YUC_FWCMD_GETRSSI_WDS             5

#define YUC_FWCMD_RSSI_RECEIVER_OFFSET    0
#define YUC_FWCMD_RSSI_RECEIVER_BITS      2
#define YUC_FWCMD_RSSI_RECEIVER_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_RECEIVER, p, w )
#define YUC_FWCMD_RSSI_RECEIVER_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_RECEIVER, p, w )

#define YUC_FWCMD_RSSI_MODE_OFFSET    2
#define YUC_FWCMD_RSSI_MODE_BITS      1
#define YUC_FWCMD_RSSI_MODE_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_MODE, p, w )
#define YUC_FWCMD_RSSI_MODE_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_MODE, p, w )

#define YUC_FWCMD_RSSI_RATE_OFFSET    4
#define YUC_FWCMD_RSSI_RATE_BITS      1
#define YUC_FWCMD_RSSI_RATE_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_RATE, p, w )
#define YUC_FWCMD_RSSI_RATE_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_RATE, p, w )

#define YUC_FWCMD_RSSI_THRESHOLD_OFFSET    8
#define YUC_FWCMD_RSSI_THRESHOLD_BITS      5
#define YUC_FWCMD_RSSI_THRESHOLD_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_THRESHOLD, p, w )
#define YUC_FWCMD_RSSI_THRESHOLD_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_THRESHOLD, p, w )

#define YUC_FWCMD_RSSI_REF_G0_0_OFFSET    0
#define YUC_FWCMD_RSSI_REF_G0_0_BITS      4
#define YUC_FWCMD_RSSI_REF_G0_0_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_G0_0, p, w )
#define YUC_FWCMD_RSSI_REF_G0_0_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_G0_0, p, w )

#define YUC_FWCMD_RSSI_REF_G0_1_OFFSET    4
#define YUC_FWCMD_RSSI_REF_G0_1_BITS      4
#define YUC_FWCMD_RSSI_REF_G0_1_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_G0_1, p, w )
#define YUC_FWCMD_RSSI_REF_G0_1_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_G0_1, p, w )

#define YUC_FWCMD_RSSI_REF_G0_2_OFFSET    8
#define YUC_FWCMD_RSSI_REF_G0_2_BITS      4
#define YUC_FWCMD_RSSI_REF_G0_2_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_G0_2, p, w )
#define YUC_FWCMD_RSSI_REF_G0_2_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_G0_2, p, w )

#define YUC_FWCMD_RSSI_REF_G1_0_OFFSET    0
#define YUC_FWCMD_RSSI_REF_G1_0_BITS      4
#define YUC_FWCMD_RSSI_REF_G1_0_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_G1_0, p, w )
#define YUC_FWCMD_RSSI_REF_G1_0_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_G1_0, p, w )

#define YUC_FWCMD_RSSI_REF_G1_1_OFFSET    4
#define YUC_FWCMD_RSSI_REF_G1_1_BITS      4
#define YUC_FWCMD_RSSI_REF_G1_1_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_G1_1, p, w )
#define YUC_FWCMD_RSSI_REF_G1_1_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_G1_1, p, w )

#define YUC_FWCMD_RSSI_REF_G1_2_OFFSET    8
#define YUC_FWCMD_RSSI_REF_G1_2_BITS      4
#define YUC_FWCMD_RSSI_REF_G1_2_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_G1_2, p, w )
#define YUC_FWCMD_RSSI_REF_G1_2_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_G1_2, p, w )

#define YUC_FWCMD_RSSI_REF_GOTHER_0_OFFSET    0
#define YUC_FWCMD_RSSI_REF_GOTHER_0_BITS      4
#define YUC_FWCMD_RSSI_REF_GOTHER_0_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_GOTHER_0, p, w )
#define YUC_FWCMD_RSSI_REF_GOTHER_0_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_GOTHER_0, p, w )

#define YUC_FWCMD_RSSI_REF_GOTHER_1_OFFSET    4
#define YUC_FWCMD_RSSI_REF_GOTHER_1_BITS      4
#define YUC_FWCMD_RSSI_REF_GOTHER_1_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_GOTHER_1, p, w )
#define YUC_FWCMD_RSSI_REF_GOTHER_1_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_GOTHER_1, p, w )

#define YUC_FWCMD_RSSI_REF_GOTHER_2_OFFSET    8
#define YUC_FWCMD_RSSI_REF_GOTHER_2_BITS      4
#define YUC_FWCMD_RSSI_REF_GOTHER_2_W2P( p, w )    YUC_W2P( YUC_FWCMD_RSSI_REF_GOTHER_2, p, w )
#define YUC_FWCMD_RSSI_REF_GOTHER_2_P2W( p, w )    YUC_P2W( YUC_FWCMD_RSSI_REF_GOTHER_2, p, w )

#endif /* ifndef __YUC_RFIC_CMD_H__ */
