// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2021-2023 NXP
 */

#ifndef _TBGEN_REGS_NEW_H_
#define _TBGEN_REGS_NEW_H_

#include "config.h"

/*
 * Two TBGEN Controller Blocks: TBGEN1, TBGEN2  16 KB each
 * TBGEN_BASE(TBGEN1) CCSR offset: 0x1120000
 * TBGEN_BASE(TBGEN2) CCSR offset: 0x1124000
 */
#define TBGEN_BASE(x)					( CCSR_BASE_ADDR + 0x1120000 + ( 0x4000 * ( x - 1 ) ) )

/*
 * Generic TBGEN Register Details
 */
#define TBGEN_RFGCR_OFFSET				0x0
#define TBGEN_CNTRL0_OFFSET				0x8
#define TBGEN_CNTRL1_OFFSET				0xC
#define TBGEN_INTSTAT_OFFSET			0x10
#define TBGEN_TISTAT_OFFSET				0x14
#define TBGEN_TS10MSHI_OFFSET			0x1C /*MSTRCNTHI value at last 10ms RFG Frame Sync*/
#define TBGEN_TS10MSLO_OFFSET			0x20 /*MSTRCNTLO value at last 10ms RFG Frame Sync */
#define TBGEN_REFCLK_PER_10MS_OFFSET	0x2C

/* General Purpose Timestamp offsets */
#define TBGEN_TSGP0HI_OFFSET			0x6D0
#define TBGEN_TSGP0LO_OFFSET			0x6D4
#define TBGEN_TSGP1HI_OFFSET			0x6D8
#define TBGEN_TSGP1LO_OFFSET			0x6DC
#define TBGEN_TSGP2HI_OFFSET			0x6E0
#define TBGEN_TSGP2LO_OFFSET			0x6E4
#define TBGEN_TSGP3HI_OFFSET			0x6E8
#define TBGEN_TSGP3LO_OFFSET			0x6EC

/* Master Counter Register offset */
#define TBGEN_MSTRCNTHI_OFFSET			0x6F0
#define TBGEN_MSTRCNTLO_OFFSET			0x6F4

/*
 * Max Type of timers e.g. AXRF,RX_ALIGNMENT,SRX_ALIGNMENT,SPI_TRIGGER,AGC_ENABLE,TIMED_INT,GPE,TDD
 */
#define	MAX_TIMER_TYPES					8

/*
 * Timer Specific TBGEN Register Details
 * TBGEN Registers can be classified into two categories:
 * 	1)TDD type
 * 	2)Non-TDD type (all other Timers)
 */

/*
 * CTRL REG OFFSET for first instance of particular timer type
 * 1.CTRL REG OFFSET for next timer instance will be calculated
 *   by adding the fixed block size.
 * 2.Other register Offsets Address  for the timer will be calculated
 *   by adding offsets in this CTRL REG OFFSET.
 */

/* AXCTRL0 */
#define AXRF_TIMER_CTRL_OFFSET			0xD0
/* RXCTRL0 */
#define RX_ALIGNMENT_TIMER_CTRL_OFFSET	0x170
/* SRXCTRL0*/
#define SRX_ALIGNMENT_TIMER_CTRL_OFFSET	0x1B0
/* SPICTRL0 */
#define SPI_TRIGGER_TIMER_CTRL_OFFSET	0x1F0
/* AGCCTRL0 */
#define AGC_TIMER_CTRL_OFFSET			0x270
/* TimedCTRL0 */
#define TIMED_INT_TIMER_CTRL_OFFSET		0x2F0
/* GeneralCTRL0 */
#define GPE_TIMER_CTRL_OFFSET			0x3C0
/* TDD0_CTRL */
#define TDD_TIMER_CTRL_OFFSET			0x450

extern const uint32_t uTimerCtrlOffset[MAX_TIMER_TYPES];

/* TDD TIMER BLOCK SIZE TO REACH NEXT TDD INSTANCE */
#define TDD_TIMER_BLOCK_SIZE			0x50

/* TDD TIMER REG OFFSETS FROM CTRL REG */
#define TDD_TIMER_HI_OFFSET				0x4
#define TDD_TIMER_LO_OFFSET				0x8
#define TDD_TIMER_MODE_OFFSET			0xC
#define TDD_TIMER_DURATION_OFFSET		0x10

/* NON TDD TIMER BLOCK SIZE TO REACH NEXT NON TDD INSTANCE */
#define TIMER_BLOCK_SIZE				0x10

/* NON TDD TIMERS REG OFFSETS FROM CTRL REG */
#define TIMER_INTRVL_OFFSET				0x4
#define TIMER_HI_OFFSET					0x8
#define TIMER_LO_OFFSET					0xC

/*
 * Register bits Related Macros
 */
/* RFG BITS */
/* CNTRL0 */
#define RFG_FRAME_SYNC_SOURCE_MASK		0b11
#define RFG_FRAME_SYNC_SOURCE_BIT		12
/* RFGCR */
#define RFG_INIT_BIT					0
#define RFG_REF_SYNC_BIT				2
#define RFG_REF_SYNC_MASK				0b1
#define RFG_START_INT_RAD_FRM_BIT		17
#define RFG_FIX_ERR_BIT					1
#define RFG_FIX_ERR_MASK				0b1
#define RFG_START_INT_RAD_FRM_MASK		0b1
#define RFG_SYNCOUT_CTRL_BIT			18
#define RFG_SYNCOUT_CTRL_MASK			0b1
#define RFG_FS_INT_MASK				0b1
#define RFG_FS_INT_BIT				5
#define RFG_ERR_INT_MASK			0b1
#define RFG_ERR_INT_BIT				4

/* TBGEN TDD INTSTAT */
#define TDD_INT_MASK_EIGHT_BITS			0xFF
#define TDDx_INT_STATUS_FLAG_START_BIT		16
#define TDDx_INT_STATUS_FLAG_MASK		( 0x00FF0000 )

/* TDD Duration */
#define TDD0_DURATION0_OFFSET			0x460

/* TDD Mode */
#define TDD0_MODE0_OFFSET			0x45C
#define TDDX_MODE_BLOCK_SIZE			0x50

/* TDD TIMER TDDx_CTRL REGBITS */
#define TDD_MODE_BIT_MASK_SIZE			2
#define TDD_MODE_BIT_MASK				0b11
#define TDD_CTRL_BUFLENGTH_BIT			4
#define TDD_CTRL_BUFLENGTH_MASK			0b1111
#define TDD_CTRL_BUFLENGTH_BIT_CLR		( 0xFFFFFF0F )
#define TDD_CTRL_CONTSEQ_BIT			1
#define TDD_CTRL_CONTSEQ_MASK			0b1
#define TDD_CTRL_CONTSEQ_BIT_CLR		( 0xFFFFFFFD )
#define TDD_CTRL_TMREN_BIT				0
#define TDD_CTRL_TMREN_MASK				0b1
#define TDD_CTRL_PULSE_MODE_BIT			10
#define TDD_CTRL_PULSE_MODE_MASK		0b11
#define TDD_CTRL_PULSE_MODE_BIT_CLR		( 0xFFFFF3FF )
#define TDD_CTRL_PULSE_WIDTH_BIT		16
#define TDD_CTRL_PULSE_WIDTH_MASK		0xFFFF
#define TDD_CTRL_PULSE_WIDTH_BIT_CLR	( 0x0000FFFF )
#define TDD_CTRL_TXRXEN_BIT				8
#define TDD_CTRL_TXRXEN_MASK			0b11
#define TDD_CTRL_TXRXEN_BIT_CLR			( 0xFFFFFCFF )

/* TDD Offset Set */
#define TDD0_OSETHI_OFFSET			0x454
#define TDD0_OSETLO_OFFSET			0x458
#define TDDX_OFFSET_BLOCK_SIZE			0x50

/* TBGEN RX ALIGNx */
#define RX_ALIGN0_INTRVL_OFFSET			0x174
#define TBGEN_RX_ALIGN0_OSETHI_OFFSET		0x178
#define TBGEN_RX_ALIGN0_OSETLO_OFFSET		0x17C
#define RX_ALIGN_CTRL_BLOCK_SIZE		0x10
#define RX_ALIGN_CTRL_TMREN_BIT			0
#define RX_ALIGN_CTRL_TMREN_MASK		0b1
#define RX_ALIGN_CTRL_PULSE_WIDTH_MASK		0b1111
#define RX_ALIGN_CTRL_PULSE_WIDTH_BIT		8
#define RX_ALIGN_CTRL_PULSE_MODE_MASK		0b11
#define RX_ALIGN_CTRL_PULSE_MODE_BIT		4
#define RX_ALIGN_CTRL_TRIG_MODE_MASK		0b1
#define RX_ALIGN_CTRL_TRIG_MODE_BIT		6	/* One Shot / Repetitive */
#define RX_ALIGN_CTRL_POLARITY_BIT		7
#define RX_ALIGN_CTRL_POLARITY_MASK		0b1

/* GP Event Control */
#define GPEX_CTRL_BLOCK_SIZE			0x10
#define GPEX_CTRL_CONTSEQ_BIT			6
#define GPEX_CTRL_CONTSEQ_MASK			0b1
#define GPE0_OSETHI_OFFSET			0x3C8
#define GPE0_OSETLO_OFFSET			0x3CC
#define GPEX_OFFSET_BLOCK_SIZE			0x10
#define GPE0_INTRVL_OFFSET			0x3C4
#define GPE_INTRVL_BLOCK_SIZE			0x10
#define GPEX_CTRL_STROBE_MODE_BIT		4
#define GPEX_CTRL_STROBE_MODE_MASK		0b11
#define GPEX_CTRL_PULSE_WIDTH_BIT		8
#define GPEX_CTRL_PULSE_WIDTH_MASK		0b1111
#define GPEX_CTRL_POLARITY_BIT			7
#define GPEX_CTRL_POLARITY_MASK			0b1
#define GPEX_CTRL_TMREN_BIT			0
#define GPEX_CTRL_TMREN_MASK			0b1

/* SRX Event Control */
#define SRXX_CTRL_BLOCK_SIZE			0x10
#define SRXX_CTRL_CONTSEQ_BIT			6
#define SRXX_CTRL_CONTSEQ_MASK			0b1
#define SRX0_OSETHI_OFFSET			0x1B8
#define SRX0_OSETLO_OFFSET			0x1BC
#define SRXX_OFFSET_BLOCK_SIZE			0x10
#define SRX0_INTRVL_OFFSET			0x1B4
#define SRX_INTRVL_BLOCK_SIZE			0x10
#define SRXX_CTRL_STROBE_MODE_BIT		4
#define SRXX_CTRL_STROBE_MODE_MASK		0b11
#define SRXX_CTRL_PULSE_WIDTH_BIT		8
#define SRXX_CTRL_PULSE_WIDTH_MASK		0b1111
#define SRXX_CTRL_POLARITY_BIT			7
#define SRXX_CTRL_POLARITY_MASK			0b1
#define SRXX_CTRL_TMREN_BIT			0
#define SRXX_CTRL_TMREN_MASK			0b1

/* AGCEN Timer Control */
#define AGCENX_CTRL_BLOCK_SIZE			0x10
#define AGCENX_CTRL_CONTSEQ_BIT			6
#define AGCENX_CTRL_CONTSEQ_MASK		0b1
#define AGCEN0_OSETHI_OFFSET			0x278
#define AGCEN0_OSETLO_OFFSET			0x27C
#define AGCENX_OFFSET_BLOCK_SIZE		0x10
#define AGCEN0_INTRVL_OFFSET			0x274
#define AGCEN_INTRVL_BLOCK_SIZE			0x10
#define AGCENX_CTRL_STROBE_MODE_BIT		4
#define AGCENX_CTRL_STROBE_MODE_MASK		0b11
#define AGCENX_CTRL_PULSE_WIDTH_BIT		8
#define AGCENX_CTRL_PULSE_WIDTH_MASK		0b1111
#define AGCENX_CTRL_POLARITY_BIT		7
#define AGCENX_CTRL_POLARITY_MASK		0b1
#define AGCENX_CTRL_TMREN_BIT			0
#define AGCENX_CTRL_TMREN_MASK			0b1

/* SRX Event Control */
#define SRXX_CTRL_BLOCK_SIZE			0x10
#define SRXX_CTRL_CONTSEQ_BIT			6
#define SRXX_CTRL_CONTSEQ_MASK			0b1
#define SRX0_OSETHI_OFFSET			0x1B8
#define SRX0_OSETLO_OFFSET			0x1BC
#define SRXX_OFFSET_BLOCK_SIZE			0x10
#define SRX0_INTRVL_OFFSET			0x1B4
#define SRX_INTRVL_BLOCK_SIZE			0x10
#define SRXX_CTRL_STROBE_MODE_BIT		4
#define SRXX_CTRL_STROBE_MODE_MASK		0b11
#define SRXX_CTRL_PULSE_WIDTH_BIT		8
#define SRXX_CTRL_PULSE_WIDTH_MASK		0b1111
#define SRXX_CTRL_POLARITY_BIT			7
#define SRXX_CTRL_POLARITY_MASK			0b1
#define SRXX_CTRL_TMREN_BIT			0
#define SRXX_CTRL_TMREN_MASK			0b1

/* TBGEN SPI */
#define SPITRIG_CTRL_BLOCK_SIZE			0x10
#define SPITRIG_CTRL_TMREN_BIT			0
#define SPITRIG_CTRL_TMREN_MASK			0b1
#define SPITRIG_CTRL_TRIG_MODE_BIT		6
#define SPITRIG_CTRL_TRIG_MODE_MASK		0b1	/* One Shot / Repetitive */
#define SPITRIG0_INTRVL_OFFSET			0x1F4
#define SPITRIG_INTRVL_BLOCK_SIZE		0x10
#define SPITRIG0_OSETHI_OFFSET			0x1F8
#define SPITRIG0_OSETLO_OFFSET			0x1FC
#define SPITRIG_BLOCK_SIZE			0x10
#define SPITRIG_CTRL_STROBE_MODE_BIT		4
#define SPITRIG_CTRL_STROBE_MODE_MASK		0b11
#define SPITRIG_CTRL_PULSE_WIDTH_BIT		8
#define SPITRIG_CTRL_PULSE_WIDTH_MASK		0b1111
#define SPITRIG_CTRL_POLARITY_BIT		7
#define SPITRIG_CTRL_POLARITY_MASK		0b1

/* NON TDD TIMER CTRL Register BITS */
#define CTRL_TMREN_BIT				0
#define CTRL_TMR_ENABLE_MASK			( 0x1 )
#define CTRL_TMR_DISABLE_MASK			( 0xFFFFFFFE )
#define CTRL_PULSE_WIDTH_MASK			0b1111
#define CTRL_PULSE_WIDTH_BIT			8
#define CTRL_PULSE_WIDTH_BIT_CLR		( 0xFFFFF0FF )
#define CTRL_STROBE_MODE_MASK			0b11
#define CTRL_STROBE_MODE_BIT			4
#define CTRL_STROBE_MODE_BIT_CLR		( 0xFFFFFFCF )
#define CTRL_TRIGGER_MASK				0b1
#define CTRL_TRIGGER_BIT				6
#define CTRL_TRIGGER_BIT_CLR			( 0xFFFFFFBF )
#define CTRL_POLARITY_BIT				7
#define CTRL_POLARITY_MASK				0b1
#define CTRL_POLARITY_BIT_CLR			( 0xFFFFFF7F )

/* TBGEN Timed Interrupt (Ruby Trigger)  */
#define TINT0_INTRVL_OFFSET				0x2F4
#define TINT0_OSETHI_OFFSET				0x2F8
#define TINT0_OSETLO_OFFSET				0x2FC
#define TINT0_INTCTR_OFFSET				0x300


/* TBGEN Clocking */
#define SCFG_CONFIG_CONTROL1_OFFSET		0x4
#define SCFG_TBGEN_DIVISOR_MASK			0b111

#define SCFG_TBGEN1_CD_EN_BIT			2
#define SCFG_TBGEN1_CD_EN_MASK			0b1
#define SCFG_TBGEN1_REF_CLK_RAT_START_BIT	6
#define SCFG_TBGEN1_REF_CLK_RAT_MASK		0b111

#define SCFG_TBGEN2_CD_EN_BIT			13
#define SCFG_TBGEN2_CD_EN_MASK			0b1
#define SCFG_TBGEN2_REF_CLK_RAT_START_BIT	17
#define SCFG_TBGEN2_REF_CLK_RAT_MASK		0b111

/* SCFG - HS & LS Clocking Divider */
#define SCFG_CONFIG_CONTROL4_OFFSET		0x20
#define SCFG_LS_DIVISOR_START_BIT		7
#define SCFG_LS_DIVISOR_MASK			0b111
#define SCFG_LS_SOC_CLK_EN_BIT			0
#define SCFG_LS_SOC_CLK_EN_BIT_MASK		0b1
#define SCFG_LS_SOC_CLK_SEL_BIT			1
#define SCFG_LS_SOC_CLK_SEL_BIT_MASK		0b1
#define SCFG_HS_DIVISOR_START_BIT		11
#define SCFG_HS_DIVISOR_MASK			0b111
#define SCFG_HS_SOC_CLK_EN_BIT			10
#define SCFG_HS_SOC_CLK_EN_BIT_MASK		0b1
/* CNTRL0 */
#define TBGEN_CTRL_TS_EN_BIT_START    4
#define TBGEN_CTRL_TS_EN_BIT_MASK     0b1
#define TBGEN_CTRL_TS_POL_BIT_START   5
#define TBGEN_CTRL_TS_POL_BIT_MASK    0b1

/* TBGEN TIMER INTERRUPT Related BITS */
/* CNTRL1 and INTSTAT */
#define TBGEN_CTRL_GPE_INT_BIT_START	8
#define TBGEN_CTRL_GPE_INT_BIT_MASK		0b1
#define TBGEN_CTRL_TDD_INT_BIT_START	16
#define TBGEN_CTRL_TDD_INT_BIT_MASK		0b1
#define TBGEN_CTRL_TS_INT_BIT_START	0
#define TBGEN_CTRL_TS_INT_BIT_MASK		0b1

#define TBGEN_CTRL_RFG_FS_INT_BIT_START	5
#define TBGEN_CTRL_RFG_FS_INT_BIT_MASK	0b1
#define TBGEN_CTRL_SWRST_BIT_START		0
#define TDD_INT_STATUS_FLAG_MASK		( 0x00FF0000 )
#define GPE_INT_STATUS_FLAG_MASK		( 0x0000FF00 )
#define TS_INT_STATUS_FLAG_MASK			( 0x0000000F )

#endif /* _TBGEN_REGS_NEW_H_ */
